<a href="https://colab.research.google.com/github/Bhushan-14/Python/blob/main/Python_15_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.DataFrame([[1,"Amit",34],[2,'Deepak',23]],columns=['id','name',"age"])

In [ ]:
df

   id    name  age
0   1    Amit   34
1   2  Deepak   23

In [ ]:
df.to_csv("fromdf.csv",index=False)
#df.to_excel("file")

In [ ]:
df1=pd.read_csv("d:\\SacramentocrimeJanuary2006.csv")

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7584 entries, 0 to 7583
Data columns (total 9 columns):
cdatetime        7584 non-null object
address          7584 non-null object
district         7584 non-null int64
beat             7584 non-null object
grid             7584 non-null int64
crimedescr       7584 non-null object
ucr_ncic_code    7584 non-null int64
latitude         7584 non-null float64
longitude        7584 non-null float64
dtypes: float64(2), int64(3), object(4)
memory usage: 533.3+ KB

In [ ]:
df1.head()

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
0,1/1/06 0:00,3108 OCCIDENTAL DR,3,3C,1115,10851(A)VC TAKE VEH W/O OWNER,2404,38.550420,-121.391416
1,1/1/06 0:00,2082 EXPEDITION WAY,5,5A,1512,459 PC BURGLARY RESIDENCE,2204,38.473501,-121.490186
2,1/1/06 0:00,4 PALEN CT,2,2A,212,10851(A)VC TAKE VEH W/O OWNER,2404,38.657846,-121.462101
3,1/1/06 0:00,22 BECKFORD CT,6,6C,1443,476 PC PASS FICTICIOUS CHECK,2501,38.506774,-121.426951
4,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY-UNSPECIFIED,2299,38.637448,-121.384613

In [ ]:
df1.isna().sum()

cdatetime        0
address          0
district         0
beat             0
grid             0
crimedescr       0
ucr_ncic_code    0
latitude         0
longitude        0
dtype: int64

In [ ]:
#np.unique(df1['district'])
df1['district'].unique()

array([3, 5, 2, 6, 4, 1], dtype=int64)

In [ ]:
df1['district'].value_counts()

3    1575
2    1462
6    1359
4    1161
5    1159
1     868
Name: district, dtype: int64

In [ ]:
#df1.apply(pd.Series.value_counts)

In [ ]:
df2=pd.read_csv("d:\\COVIDclinicaltrials.csv",header=None)

In [ ]:
df2

,0,1,2,3,4,5,6,7,8,9,...,17,18,19,20,21,22,23,24,25,26
0,Rank,NCT Number,Title,Acronym,Status,Study Results,Conditions,Interventions,Outcome Measures,Sponsor/Collaborators,...,Other IDs,Start Date,Primary Completion Date,Completion Date,First Posted,Results First Posted,Last Update Posted,Locations,Study Documents,URL
1,1,NCT04395924,Maternal-foetal Transmission of SARS-Cov-2,TMF-COVID-19,Recruiting,No Results Available,Maternal Fetal Infection Transmission|COVID-19...,Diagnostic Test: Diagnosis of SARS-Cov2 by RT-...,COVID-19 by positive PCR in cord blood and / o...,Centre Hospitalier Régional d'Orléans|Centre d...,...,CHRO-2020-10,"May 5, 2020",May 2021,May 2021,"May 20, 2020",NaN,"June 4, 2020","CHR Orléans, Orléans, France",NaN,https://ClinicalTrials.gov/show/NCT04395924
2,2,NCT04395482,Lung CT Scan Analysis of SARS-CoV2 Induced Lun...,TAC-COVID19,Recruiting,No Results Available,covid19,Other: Lung CT scan analysis in COVID-19 patients,A qualitative analysis of parenchymal lung dam...,University of Milano Bicocca,...,TAC-COVID19,"April 15, 2020","June 15, 2020","October 15, 2020","May 20, 2020",NaN,"May 26, 2020","Ospedale Papa Giovanni XXIII, Bergamo, Italy|P...",NaN,https://ClinicalTrials.gov/show/NCT04395482
3,3,NCT04367805,COVID-19 Infection in Patients With Hepatocell...,COVID19-CHIEF,Recruiting,No Results Available,Hepatocellular Carcinoma|COVID-19,Diagnostic Test: nasopharyngeal Covid 19 RT-PCR,Incidence of COVID-19 infection in patients wi...,"Centre Hospitalier Universitaire, Amiens|Centr...",...,PI2020_843_0042,"April 27, 2020",October 2020,October 2020,"April 29, 2020",NaN,"April 29, 2020","CHU Amiens, Amiens, France",NaN,https://ClinicalTrials.gov/show/NCT04367805
4,4,NCT04427332,Smell and Taste Disorders in COVID-19 Patients,COVID-19 ORL,Recruiting,No Results Available,covid19,Other: Investigation of smell and taste disorders,Identification of demographic and clinical fac...,University of Milano Bicocca,...,COVID-19 ORL,"May 15, 2020","June 30, 2020","September 30, 2020","June 11, 2020",NaN,"June 11, 2020","ASST Monza-Ospedale San Gerardo, Monza, Italy",NaN,https://ClinicalTrials.gov/show/NCT04427332
5,5,NCT04407585,Testing the Accuracy of a Digital Test to Diag...,NaN,Recruiting,No Results Available,Covid-19,Diagnostic Test: Covid-19 swab PCR test,SARS-CoV-2 infection,King's College London|Zoe Global Limited|Depar...,...,Covid-19 Validation Study,"June 1, 2020","May 10, 2021","May 10, 2021","May 29, 2020",NaN,"June 24, 2020","King's College London, London, United Kingdom","""Statistical Analysis Plan"", https://ClinicalT...",https://ClinicalTrials.gov/show/NCT04407585
6,6,NCT04403672,Performance Evaluation of RealDetect™ COVID-19...,NaN,Recruiting,No Results Available,High Sensitivity and Specificity (With 95% Con...,Device: performance evaluation study of RealDe...,Performance evaluation of RealDetect™ COVID-19...,Bangladesh Medical Research Council (BMRC),...,30005052020,"May 18, 2020","July 24, 2020","July 24, 2020","May 27, 2020",NaN,"May 28, 2020","Institute of Epidemiology, Disease Control and...",NaN,https://ClinicalTrials.gov/show/NCT04403672
7,7,NCT04372004,Comparison of the Efficacy of Rapid Tests to I...,CATCH COVID-19,Not yet recruiting,No Results Available,COVID-19,Diagnostic Test: diagnostic tests for COVID-19...,Compare the efficacy of detection of viral inf...,Texas Cardiac Arrhythmia Research Foundation,...,TCAI_CATCH COVID-19,May 2020,May 2021,June 2021,"May 1, 2020",NaN,"May 8, 2020",NaN,NaN,https://ClinicalTrials.gov/show/NCT04372004
8,8,NCT04416061,The Role of a Private Hospital in Hong Kong Am...,COVID-19,"Active, not recruiting",No Results Available,COVID,Diagnostic Test: COVID 19 Diagnostic Test,Proportion of asymptomatic subjects|Proportion...,Hong Kong Sanatorium & Hospital,...,RC-2020-08,"May 25, 2020","July 31, 2020","August 31, 2020","June 4, 2020",NaN,"June 4, 2020","Hong Kong Sanatorium & Hospital, Hong Kong, Ho...",NaN,https://ClinicalTrials.gov/show/NCT04416061
9,9,NCT04386109,Neonatal Complications of Coronavirus Disease ...,NaN,Recruiting,No Results Available,Neonatal COVID-19 Disease,Other: No intervention - exposure is to COVID-19,Incidence of neonatal COVID-19|Incidence of ve...,University of Oxford|Imperial College London|U...,...,14905,"April 1, 2020","March 31, 2021","September 30, 2021","May 13, 2020",NaN,"May 13, 2020","Imperial College, London, United Kingdom",NaN,https://ClinicalTrials.gov/show/NCT04386109
10,10,NCT04424004,MURDOCK Cabarrus County COVID-19 Prevalence an...,C3PI,Enrolling by invitation,No Results Available,COVID 19,Other: COVID-19 PCR and serology testing,Estimate the prevalence of COVID-19 infection ...,Duke University|North Carolina Department of H...,...,Pro00105703,"June 9, 2020","June 30, 2021","June 30, 2021","June 9, 2020",NaN,"July 8, 2020",Duke CTSI Translational Population Health Offi...,NaN,https://ClinicalTrials.gov/show/NCT04424004
11,11,NCT04356560,COVID-19 Surveillance of Patients and Healthca...,NaN,Enrolling by invitation,No Results Available,COVID-19,"Diagnostic Test: COVID-19 test, polymerase cha...",Incidence of healthcare workers with SARS-CoV-...,"Rigshospitalet, Denmark",...,DT P-2020-353,"March 23, 2020","September 30, 2020","December 31, 2020","April 22, 2020",NaN,"April 24, 2020",Rigshospitalet University Hospital of Copenhag...,NaN,https://ClinicalTrials.gov/show/NCT04356560
12,12,NCT04390074,COVID-19 in the Swedish ICU-cohort: Risk Facto...,NaN,Not yet recruiting,No Results Available,COVID-19|Critical Illness,Other: COVID-19 and Intensive Care,Chronic medications as risk factor of intensiv...,Uppsala University|Center for Clinical Researc...,...,UTN: U1111-1251-8195,June 2020,June 2020,June 2020,"May 15, 2020",NaN,"May 21, 2020",NaN,NaN,https://ClinicalTrials.gov/show/NCT04390074
13,13,NCT04360811,"Assessment of Obstetric, Fetal and Neonatal Ri...",COroFet,Recruiting,No Results Available,Pregnancy,Diagnostic Test: COVID 19 diagnostic test by PCR,number of positive COVID-19 women,"University Hospital, Toulouse",...,RC31/20/0123,"April 17, 2020",April 2021,April 2022,"April 24, 2020",NaN,"April 24, 2020","University Hospital of Toulouse, Toulouse, France",NaN,https://ClinicalTrials.gov/show/NCT04360811
14,14,NCT04353206,Convalescent Plasma in ICU Patients With COVID...,NaN,Recruiting,No Results Available,Covid-19|Sars-CoV2,Biological: Multiple Doses of Anti-SARS-CoV-2 ...,Proportion of subjects who consent to the stud...,Noah Merin|Johns Hopkins University|Cedars-Sin...,...,Acute Care CP Consortium Trial,May 2020,May 2021,May 2021,"April 20, 2020",NaN,"May 14, 2020","8700 Beverly Blvd., Los Angeles, California, U...",NaN,https://ClinicalTrials.gov/show/NCT04353206
15,15,NCT04339322,Characteristics and Outcome of Coronavirus Dis...,COVID-19,Not yet recruiting,No Results Available,"Characteristics Diseases|Outcome, Fatal",Other: Follow up,Demographics of Coronavirus Disease 2019 (COVI...,Assiut University,...,COVID-19 in Egypt,"May 1, 2020","July 30, 2020","July 30, 2020","April 9, 2020",NaN,"April 9, 2020",NaN,NaN,https://ClinicalTrials.gov/show/NCT04339322
16,16,NCT04453748,"The Assessment of the Prevalence, Clinical Cou...",NaN,Enrolling by invitation,No Results Available,COVID-19|Coronavirus Infection|Sars-CoV2|Compl...,Other: Complex diagnostic panel,Prevalence of COVID-19 complications|Assessmen...,Silesian Centre for Heart Diseases|Medical Uni...,...,COVID-19 Complications Study,"June 8, 2020","October 31, 2021","November 30, 2021","July 1, 2020",NaN,"July 1, 2020","Silesian Centre for Heart Disease, Zabrze, Sil...",NaN,https://ClinicalTrials.gov/show/NCT04453748
17,17,NCT04323787,Viral Infection and Respiratory Illness Univer...,COVID-19,Recruiting,No Results Available,Coronavirus,Other: observational,ICU and hospital mortality of COVID-19 patient...,Mayo Clinic,...,20-002610,"March 30, 2020","April 30, 2021","April 30, 2021","March 27, 2020",NaN,"April 14, 2020","Mayo Clinic in Arizona, Scottsdale, Arizona, U...",NaN,https://ClinicalTrials.gov/show/NCT04323787
18,18,NCT04330261,Clinical Characteristics and Outcomes of Pedia...,PERN-COVID-19,Recruiting,No Results Available,COVID-19|SARS-CoV-2 Infection|Pediatric ALL|Pn...,Other: Exposure (not intervention) - SARS-CoV-...,Clinical characteristics of children with SARS...,University of Calgary,...,REB18-0107_MOD9,"March 18, 2020","March 17, 2021","March 17, 2022","April 1, 2020",NaN,"April 1, 2020",University of Calgary/Alberta Children's Hospi...,NaN,https://ClinicalTrials.gov/show/NCT04330261
19,19,NCT04387929,Detection of Anti-COVID-19 Antibody Levels in ...,NaN,Recruiting,No Results Available,COVID-19,Diagnostic Test: Detection of anti-COVID-19 an...,SARS-CoV-2 levels of IgG antibodies|SARS-CoV-2...,Istituto Clinico Humanitas,...,1374 IgG COVID-19 HUMANITAS,"May 4, 2020","May 30, 2021","May 30, 2021","May 14, 2020",NaN,"May 15, 2020","Humanitas Rozzano/San Pio X, Rozzano, Lombardi...",NaN,https://ClinicalTrials.gov/show/NCT04387929
20,20,NCT04379310,Evaluation of Clinical Parameters on Admission...,Covid-19,Completed,No Results Available,Covid-19,Drug: ACE Inhibitors and Calcium Channel Blockers,extend of lung involvement|oxygen saturation o...,Nisantasi University,...,20200504441,"May 1, 2020","May 5, 2020","May 8, 2020","May 7, 2020",NaN,"June 5, 2020","Vital Hospital, Bahcelievler, Istanbul, Turkey",NaN,https://ClinicalTrials.gov/show/NCT04379310
21,21,NCT04376996,Slovenian National COVID-19 Prevalence Study,SLO-COVID-19,Recruiting,No Results Available,COVID-19|SARS-CoV-2,Diagnostic Test: NO intervention planned due t...,Prevalence of SARS-CoV-2 RNA in nasopharyngeal...,University of Ljubljana,...,ULMF2020-COVID-19,"April 20, 2020",October 2020,December 2020,"May 6, 2020",NaN,"May 7, 2020","University of Ljubljana, Ljubljana, Slovenia",NaN,https://ClinicalTrials.gov/show/NCT04376996
22,22,NCT04342637,COVID-19 Endoscopy Survey,COVID-19 Endo,Completed,No Results Available,COVID-19,Other: Practice details,Effect of GI societies recommendations on prev...,Al-Azhar University,...,WES-2,"April 10, 2020","April 25, 2020","May 1, 2020","April 13, 2020",NaN,"May 20, 2020","Kings County Hospital Center, Brooklyn, NY, US...",NaN,https://ClinicalTrials.gov/show/NCT04342637
23,23,NCT04355897,CoVID-19 Plasma in Treatment of COVID-19 Patients,NaN,Recruiting,No Results Available,COVID 19,Biological: Convalescent COVID 19 Plasma,Reduce mortality|Reduce requirement for mechan...,The Christ Hospital,...,20-23,"April 28, 2020",July 2020,August 2020,"April 21, 2020",NaN,"May 20, 2020","The Christ Hospital, Cincinnati, Ohio, United ...",NaN,https://ClinicalTrials.gov/show/NCT04355897
24,24,NCT04460274,Forecast Number of Covid-19 Cases Worldwide,Covid19TmeSer,Completed,No Results Available,Covid-19,Other: Model Building|Other: Model validation,Number of Confirmed cases of Covid-19,Turkish Ministry of Health Izmir Teaching Hosp...,...,TurkishMOHITH-TimeSeries,"December 31, 2019","June 15, 2020","June 20, 2020","July 7, 2020",NaN,"July 8, 2020","Republic of Turkey, Health Sciences University...",NaN,https://ClinicalTrials.gov/show/NCT04460274
25,25,NCT04392323,Incidence of COVID-19 Test Conversion in Post-...,NaN,Recruiting,No Results Available,Sars-CoV2,Diagnostic Test: COVID-19 PCR and Serology,COVID-19 Test Conversion|Duration of Hospitali...,Northwell Health,...,IRB #20-0404,"May 13, 2020","July 1, 2020","July 31, 2020","May 18, 2020",NaN,"May 18, 2020","North Shore University Hospital, Manhasset, Ne...",NaN,https://ClinicalTrials.gov/show/NCT04392323
26,26,NCT04404062,Validation of COVID-19 Tests,NaN,"Active, not recruiting",No Results Available,COVID-19,Diagnostic Test: Covid-19 Rapid Test Kit (RAPG...,Identification of asymptomatic carriers of SAR...,Richmond Pharmacology Limited,...,C20010,"March 16, 2020",August 2020,August 2020,"May 27, 2020",NaN,"May 27, 2020","Richmond Pharmacology Ltd. 1a Newcomen St, Lon...",NaN,https://ClinicalTrials.gov/show/NCT04404062
27,27,NCT04437940,Evaluation of Vaginal Fluid for Covid-19 Posit...,NaN,Recruiting,No Results Available,COVID|Sars-CoV2,Diagnostic Test: Vaginal fluid Covid-19 PCR test,Vaginal fluid Covid-19 PCR test result|becomin...,Acibadem University,...,Acibadem Maslak Ob&Gyn,"June 15, 2020","July 10, 2020","July 30, 2020","June 18, 2020",NaN,"June 18, 2020","Acibadem Maslak Hospital, Istanbul, Turkey",NaN,https://ClinicalTrials.gov/show/NCT04437940
28,28,NCT04352764,ANTIBODY BASED TESTS FOR SARSCoV-2 COVID-19) -...,NaN,Recruiting,No Results Available,Covid19,Diagnostic Test: CoronaCideTM COVID-19 IgM/IgG...,prevalence of COVID-19 exposure|correlation be...,Texas Cardiac Arrhythmia Research Foundation,...,TCAI_COVID-19,"March 27, 2020","December 31, 2020","January 31, 2021","April 20, 2020",NaN,"April 27, 2020","St. David's Medical Center, Austin, Texas, Uni...",NaN,https://ClinicalTrials.gov/show/NCT04352764
29,29,NCT04345679,Anti COVID-19 Convalescent Plasma Therapy,NaN,Not yet recruiting,No Results Available,COVID 19,Biological: anti-SARS-CoV-2 convalescent plasma,Changing of viral load of SARS-CoV2|Changes in...,Orthosera Kft.|Semmelweis University|Universit...,...,AntiCOVID19ORT,"April 14, 2020","June 1, 2020","April 1, 2021","April 14, 2020",NaN,"April 24, 2020",NaN,NaN,https://ClinicalTrials.gov/show/NCT04345679
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2566,2566,NCT04444986,Bioequivalence Study of Favir 200 mg Film Tabl...,NaN,Completed,No Results Available,Bioequivalence,Drug: FAVIR 200 MG FT|Drug: AVIGAN 200 mg FT,AUC0-tlast of favipiravir|Cmax of favipiravir|...,Kocak Farma|Novagenix Bioanalytical Drug R&D C...,...,NOV2020/01919,"June 5, 2020","June 11, 2020","June 13, 2020","June 24, 2020",NaN,"June 24, 2020","Novagenix Drug R&D Center, Akyurt, Ankara, Tur...",NaN,https://ClinicalTrials.gov/show/NCT04444986
2567,2567,NCT03260140,DVD Lifestyle Intervention,D-ELITE,"Active, not recruiting",No Results Available,Obesity,Behavioral: behavioral lifestyle intervention,body weight change|SF-12 change|International ...,VA Office of Research and Development,...,IIR 15-364|I01HX002113,"February 15, 2018","April 1, 2021","June 30, 2021","August 24, 2017",NaN,"June 23, 2020",VA Puget Sound Health Care System Seattle Divi...,NaN,https://ClinicalTrials.gov/show/NCT03260140
2568,2568,NCT04408651,Low Intensity Internet Therapy for Chronic Ill...,@LIITCI,"Active, not recruiting",No Results Available,Chronic Medical Conditions,Behavioral: LIIT.CI ACT|Behavioral: LIIT.CI CFT,Depression and anxiety (Hospital Anxiety and D...,University of Coimbra,...,LIIT,"May 1, 2020","December 31, 2020","August 31, 2021","May 29, 2020",NaN,"May 29, 2020","Inês Trindade, Coimbra, Portugal",NaN,https://ClinicalTrials.gov/show/NCT04408651
2569,2569,NCT04424212,ICBT for Mental Health Problems Related to the...,NaN,Recruiting,No Results Available,Depression and Quality of Life Related to the ...,Behavioral: Intervention group CoronaCope,Becks Depression Inventory-II|Brunnsviken Brie...,Linkoeping University,...,CoronaCope,"June 10, 2020",August 2020,August 2021,"June 9, 2020",NaN,"June 11, 2020","Linköping University, Linköping, Östergötland,...",NaN,https://ClinicalTrials.gov/show/NCT04424212
2570,2570,NCT04193020,"Acute and Chronic Inflammatory Disease, Lifest...",ACID LTR,Recruiting,No Results Available,Uveitis,Other: Surveillance card,Treatment success|Recurrence time|Severe visua...,Wroclaw Medical University|Wrocław University ...,...,ST-859,"January 1, 2020","January 1, 2025","January 1, 2026","December 10, 2019",NaN,"April 10, 2020","Department of Ophthalmology, Wrocław, Poland",NaN,https://ClinicalTrials.gov/show/NCT04193020
2571,2571,NCT02901041,Interdisciplinary Study of A Novel Anticonvuls...,NaN,"Active, not recruiting",No Results Available,Alcohol Dependence,Drug: Zonisamide|Behavioral: Take Control|Drug...,Alcohol Consumption|Risk Task - Risk Taking Be...,Boston University Charles River Campus|Mclean ...,...,2R01AA015923-06,"September 21, 2017",February 2021,August 2021,"September 15, 2016",NaN,"April 28, 2020",Center for Anxiety and Related Disorders - Bos...,NaN,https://ClinicalTrials.gov/show/NCT02901041
2572,2572,NCT04406194,Bioequivalence Study of Favipiravir 200 mg Fil...,Favipiravir,"Active, not recruiting",No Results Available,Bioequivalence,Drug: Favipiravir 200 mg,Primary PK End Points|Secondary PK End Points,Atabay Kimya Sanayi Ticaret A.S.|Novagenix Bio...,...,NOV2020/1917,"May 14, 2020","May 22, 2020","May 30, 2020","May 28, 2020",NaN,"June 4, 2020","Novagenix Drug R&D Center, Akyurt, Ankara, Tur...",NaN,https://ClinicalTrials.gov/show/NCT04406194
2573,2573,NCT04400682,Bioequivalence Study of Favipiravir 200 mg Fil...,Favipiravir,"Active, not recruiting",No Results Available,Bioequivalence,Drug: Test Drug 200 mg favipiravir|Drug: Refer...,AUC0-tlast of favipiravir will be obtained fro...,Novelfarma Ilaç San. ve Tic. Ltd. Sti.|Novagen...,...,NOV2020/1923,"May 28, 2020","June 5, 2020","July 17, 2020","May 22, 2020",NaN,"June 17, 2020","Novagenix Drug R&D Center, Akyurt, Ankara, Tur...",NaN,https://ClinicalTrials.gov/show/NCT04400682
2574,2574,NCT04144231,Cognitive Behavioral Therapy for Insomnia (CBT...,SLEEPINS,Recruiting,No Results Available,Insomnia|Schizophrenia|Schizoaffective Disorder,Behavioral: iCBT-I|Behavioral: GCBT-I,Change in Insomnia Severity Index score (ISI) ...,Helsinki University Central Hospital|Universit...,...,"1129003, TYH2018219, 30000","December 19, 2019","September 6, 2024","September 6, 2024","October 30, 2019",NaN,"April 6, 2020","Helsinki University Central Hospital, Helsinki...",NaN,https://ClinicalTrials.gov/show/NCT04144231
2575,2575,NCT04025580,Systems Analyses of the Immune Response to the...,NaN,Recruiting,No Results Available,Healthy Volunteer,Biological: Flucelvax|Biological: Fluvirin|Bio...,Microneutralization titers,National Institute of Allergy and Infectious D...,...,190126|19-I-0126,"October 2, 2019","December 31, 2025","December 31, 2025","July 19, 2019",NaN,"June 30, 2020","National Institutes of Health Clinical Center,...",NaN,https://ClinicalTrials.gov/show/NCT04025580
2576,2576,NCT04448028,Stop of Proton-pump Inhibitor Treatment in Pat...,STOPPIT,Not yet recruiting,No Results Available,Liver Cirrhosis,Drug: Placebo|Drug: Esomeprazole 20mg,Timepoint of first unplanned re-hospitalizatio...,Universitätsklinikum Hamburg-Eppendorf|German ...,...,STOPPIT-01|2019-005008-16|DRKS00021290|U1111-1...,September 2020,August 2024,August 2024,"June 25, 2020",NaN,"June 25, 2020","University Medical Center Hamburg-Eppendorf, H...",NaN,https://ClinicalTrials.gov/show/NCT04448028
2577,2577,NCT04390542,Intervention for Caregivers of Patients Underg...,NaN,Not yet recruiting,No Results Available,Blood Cancer,Behavioral: Psychoeducation,Time to identify and recruit dyads in months|A...,Case Comprehensive Cancer Center,...,CASE8Z20,"July 17, 2020","February 28, 2021","February 28, 2021","May 15, 2020",NaN,"May 15, 2020","University Hospitals Cleveland Medical Center,...",NaN,https://ClinicalTrials.gov/show/NCT04390542
2578,2578,NCT03620409,Identification of Cardiovascular and Molecular...,ICROS,Recruiting,No Results Available,Sepsis|Septic Cardiomyopathy|Cardiomyopathies,NaN,Mortality differences between septic patients ...,Jena University Hospital|Department of Anesthe...,...,ZKSJ106-V1.3|DRKS00013347,"May 9, 2018",December 2020,June 2021,"August 8, 2018",NaN,"March 27, 2020","NWG Translational Septomics, Zentrum für Innov...",NaN,https://ClinicalTrials.gov/show/NCT03620409
2579,2579,NCT04326309,Audio Data Collection for Identification and C...,NaN,Recruiting,No Results Available,COVID-19|Coronavirus Infections|Hay Fever|Asth...,NaN,Dataset size|Cough sound identification|Improv...,HealthMode Inc.,...,HM070102,"March 25, 2020","September 25, 2022","September 25, 2022","March 30, 2020",NaN,"March 30, 2020","Virtual Facility, Bronx, New York, United States",NaN,https://ClinicalTrials.gov/show/NCT04326309

In [ ]:
df1.describe()

          district         grid  ucr_ncic_code     latitude    longitude
count  7584.000000  7584.000000    7584.000000  7584.000000  7584.000000
mean      3.574631   916.250791    4275.068829    38.559809  -121.463832
std       1.642512   407.436310    2171.593193     0.056101     0.034621
min       1.000000   102.000000     909.000000    38.437999  -121.555832
25%       2.000000   567.000000    2309.000000    38.518476  -121.489543
50%       3.000000   899.000000    3532.000000    38.559523  -121.465459
75%       5.000000  1264.000000    7000.000000    38.610361  -121.435947
max       6.000000  1661.000000    8102.000000    38.683789  -121.365238

In [ ]:
df1.sort_values('district')

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
4367,1/18/06 22:00,1671 W EL CAMINO AVE,1,1B,434,10851(A)VC TAKE VEH W/O OWNER,2404,38.613539,-121.499806
1425,1/7/06 0:30,4601 BLACKROCK DR,1,1A,136,459 PC BURGLARY VEHICLE,2299,38.657333,-121.495213
1420,1/7/06 0:01,5948 MEEKS WAY,1,1A,106,1708 US THEFT OF MAIL,2310,38.683789,-121.496349
1411,1/7/06 0:00,3260 NORDYKE DR,1,1C,418,459 PC BURGLARY VEHICLE,2299,38.626506,-121.476455
1409,1/7/06 0:00,3410 SHADOW TREE DR,1,1B,401,10851(A)VC TAKE VEH W/O OWNER,2404,38.628525,-121.505960
1405,1/6/06 23:30,1911 BANDON WAY,1,1B,411,10851(A)VC TAKE VEH W/O OWNER,2404,38.626315,-121.505472
1399,1/6/06 22:49,3224 NORTHSTEAD DR,1,1C,418,CASUALTY REPORT,7000,38.626162,-121.479786
1392,1/6/06 22:30,1510 PEBBLEWOOD DR,1,1C,425,10851(A)VC TAKE VEH W/O OWNER,2404,38.621307,-121.495891
1391,1/6/06 22:26,3561 TRUXEL RD,1,1A,337,JUVENILE DISURBANCE - I RPT,7000,38.634492,-121.502849
6550,1/27/06 17:45,3285 AZEVEDO DR,1,1B,410,10851(A)VC TAKE VEH W/O OWNER,2404,38.626808,-121.509693
1383,1/6/06 22:00,6 SOUTHBURY WAY,1,1A,113,594(B)(2)(A) VANDALISM/ -$400,2999,38.670873,-121.522963
6552,1/27/06 17:46,3301 FONG RANCH RD,1,1B,404,GANG ACTIVITY - I RPT,7000,38.630207,-121.496000
4873,1/20/06 20:00,1570 WATERWHEEL DR,1,1B,444,594(B)(2)(A) VANDALISM/ -$400,2999,38.610354,-121.496060
1379,1/6/06 22:00,6 SAGINAW CIR,1,1C,414,10851(A)VC TAKE VEH W/O OWNER,2404,38.624845,-121.497487
6554,1/27/06 18:00,TRUXEL RD / DEL PASO RD,1,1A,145,TRAFFIC-ACCIDENT-NON INJURY,5400,38.655999,-121.512052
4872,1/20/06 20:00,17 DEROW CT,1,1B,435,10851(A)VC TAKE VEH W/O OWNER,2404,38.614717,-121.496711
6556,1/27/06 18:00,3100 NORMINGTON DR,1,1C,418,594(B)(2)(A) VANDALISM/ -$400,2999,38.622969,-121.480692
1366,1/6/06 21:00,3131 SPARROW DR,1,1A,344,10851(A)VC TAKE VEH W/O OWNER,2404,38.630872,-121.530806
4896,1/20/06 22:00,110 LUNA GRANDE CIR,1,1B,401,10851(A)VC TAKE VEH W/O OWNER,2404,38.628163,-121.499109
6557,1/27/06 18:00,4800 WESTLAKE PKWY,1,1A,130,THREATS - I RPT,7000,38.657985,-121.541883
3641,1/16/06 8:00,819 POTOMAC AVE,1,1C,418,594(B)(2)(A) VANDALISM/ -$400,2999,38.622605,-121.480831
6520,1/27/06 16:00,123 RIVER RUN CIR,1,1C,426,594(B)(2)(A) VANDALISM/ -$400,2999,38.620116,-121.489333
1492,1/7/06 9:59,2814 ROSEAU WAY,1,1B,421,487(A) GRAND THEFT-INSIDE,2308,38.617953,-121.521549
6478,1/27/06 13:12,300 BOWMAN AVE,1,1C,429,PROB VIOLA/FEL-MISD - I RPT,7000,38.617479,-121.470606
3613,1/16/06 0:01,1921 OAK BLUFF WAY,1,1B,423,484 PC PETTY THEFT,2399,38.620346,-121.504936
3614,1/16/06 0:01,3356 LA CADENA WAY,1,1A,102,POSSIBLE FINANCIAL CRIME-I RPT,7000,38.680984,-121.535913
4910,1/20/06 23:00,3301 LONG BRANCH CT,1,1B,401,459 PC BURGLARY VEHICLE,2299,38.628260,-121.509379
6488,1/27/06 14:00,1818 CLAYTON WAY,1,1A,136,VANDALISM - I RPT,7000,38.657990,-121.500447
4909,1/20/06 23:00,4500 TRUXEL RD,1,1A,306,459 PC BURGLARY VEHICLE,2299,38.653572,-121.509513
6492,1/27/06 14:16,ARENA BLVD / I 5 NB,1,1A,305,TRAFFIC-ACCIDENT INJURY,5400,38.642998,-121.519435
...,...,...,...,...,...,...,...,...,...
1588,1/7/06 18:13,64TH ST / 21ST AVE,6,6B,1068,10851 VC AUTO THEFT LOCATE,2404,38.532321,-121.429494
3090,1/13/06 16:47,7949 CARLTON RD,6,6C,1133,459 PC BURGLARY-UNSPECIFIED,2299,38.538303,-121.410598
6397,1/27/06 5:45,7341 ROTELLA DR,6,6C,1404,459 PC BURGLARY VEHICLE,2299,38.517674,-121.418485
6426,1/27/06 9:40,3632 52ND ST,6,6B,1054,243(E)1 BATTERY NONCOHAB SPOUS,1315,38.541001,-121.445815
3087,1/13/06 16:33,34TH ST / 21ST AVE,6,6A,1061,11364 HS POSS DRUG PARAPH,3599,38.533625,-121.470525
3104,1/13/06 18:00,15 CARTHAGE CT,6,6C,1443,MISSING PERSON,7000,38.505769,-121.418114
1551,1/7/06 15:25,STOCKTON BLVD / 48TH AVE,6,6C,1441,TRAFFIC-ACCIDENT-NON INJURY,5400,38.509468,-121.435394
3136,1/13/06 20:00,19TH AVE / 36TH ST,6,6A,1061,245(A)(2) AWDW/FIREARM/CIVILIA,1315,38.535386,-121.468201
3135,1/13/06 19:56,5610 STOCKTON BLVD,6,6B,1401,211 PC ROBBERY- BUSINESS,1299,38.524395,-121.442857
1516,1/7/06 12:03,79TH ST / TORONTO WAY,6,6C,1133,TRAFFIC-ACCIDENT INJURY,5400,38.531619,-121.412628
1517,1/7/06 12:09,3129 SAN JOSE WAY,6,6A,1032,212.5(A)ROBBERY-INHAB DWELLING,1299,38.546210,-121.459268
1519,1/7/06 12:16,4328 62ND ST,6,6B,1067,CASUALTY REPORT,7000,38.535252,-121.433011
3133,1/13/06 19:45,5041 46TH ST,6,6B,1084,594(B)(1)PC VANDALISM +$400,2999,38.529635,-121.452073
1524,1/7/06 13:00,5201 9TH AVE,6,6B,1035,484 PETTY THEFT/LICENSE PLATE,2399,38.543742,-121.445363
3130,1/13/06 19:30,4132 55TH ST,6,6B,1065,MISCELLANEOUS I RPT (ZMISC),7000,38.536514,-121.442416
6449,1/27/06 11:15,US 50 EB / 59TH ST,6,6B,1018,MISSING PERSON,7000,38.553093,-121.436615
5231,1/22/06 13:36,7541 38TH AVE,6,6C,1404,PROTECTIVE CUSTODY-I RPT,7000,38.519114,-121.415894
1526,1/7/06 13:09,7961 53RD AVE,6,6C,1445,243(E)1 BATTERY NONCOHAB SPOUS,1315,38.503897,-121.409697
3128,1/13/06 19:19,2500 35TH ST,6,6A,1013,529 PC FALSE PERSONATION,2604,38.554516,-121.467436
1533,1/7/06 14:00,4315 MARTIN LUTHER KING JR BLVD,6,6A,1062,459 PC BURGLARY BUSINESS,2203,38.535806,-121.462349
3125,1/13/06 19:05,5095 STOCKTON BLVD,6,6B,1086,594(B)(1)PC VANDALISM +$400,2999,38.528683,-121.443753
3124,1/13/06 19:00,6813 BENDER CT,6,6C,1131,459 PC BURGLARY VEHICLE,2299,38.534362,-121.424590
1538,1/7/06 14:13,7931 CAPISTRANO WAY,6,6C,1424,THREATS - I RPT,7000,38.511873,-121.411158
6437,1/27/06 10:36,6043 POWER INN RD,6,6C,1406,10851 VC AUTO THEFT LOCATE,2404,38.517492,-121.409025
1544,1/7/06 15:00,4820 76TH ST,6,6C,1143,CASUALTY REPORT,7000,38.531678,-121.416218
3108,1/13/06 18:00,3264 RAMONA AVE,6,6C,1113,10851(A)VC TAKE VEH W/O OWNER,2404,38.545224,-121.415719
3105,1/13/06 18:00,15 CARTHAGE CT,6,6C,1443,MISSING PERSON,7000,38.505769,-121.418114
6430,1/27/06 9:45,8151 POWER RIDGE RD,6,6C,1145,10851 VC AUTO THEFT LOCATE,2404,38.531579,-121.407542
1553,1/7/06 16:10,3946 2ND AVE,6,6A,1014,459 PC BURGLARY RESIDENCE,2204,38.550676,-121.461860
3791,1/16/06 22:00,5961 13TH AVE,6,6B,1056,459 PC BURGLARY VEHICLE,2299,38.540424,-121.436176

In [ ]:
df1.sort_values('district',ascending=False)

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
5428,1/23/06 10:44,3012 REDDING AVE,6,6C,1111,TOWED/STORED VEHICLE,7000,38.546570,-121.423442
1134,1/5/06 20:15,16TH AVE / STOCKTON BLVD,6,,1064,23220 VC DRINKING WHILE DRVING,5404,38.537896,-121.448870
2313,1/10/06 22:00,1 CLAUSS CT,6,6B,1084,10851(A)VC TAKE VEH W/O OWNER,2404,38.529359,-121.447171
6064,1/25/06 19:30,4592 58TH ST,6,6B,1065,MISSING PERSON,7000,38.533681,-121.438691
4418,1/19/06 7:46,130 PRAIRIE CIR,6,6C,1443,11350(B)HS POSSESS QUAALUDES,3582,38.509602,-121.417646
2316,1/10/06 22:00,8155 BELVEDERE AVE,6,6C,1134,484 PETTY THEFT/LICENSE PLATE,2399,38.538760,-121.406573
2318,1/10/06 22:15,ALHAMBRA BLVD / BROADWAY,6,6A,1001,647(B) PC PROSTITUTION,4004,38.556123,-121.472436
6071,1/25/06 20:00,5408 56TH ST,6,6B,1086,10851(A)VC TAKE VEH W/O OWNER,2404,38.525689,-121.440578
1126,1/5/06 20:00,3015 SAN CARLOS WAY,6,6A,1032,459 PC BURGLARY RESIDENCE,2204,38.546543,-121.461195
6072,1/25/06 20:13,4609 13TH AVE,6,6A,1053,TOWED/STORED VEHICLE,7000,38.540580,-121.452674
2320,1/10/06 22:23,2ND AVE / 57TH ST,6,6B,1018,11357(B)HS POSS -28.5GR MARIJ,3562,38.550802,-121.439210
4413,1/19/06 6:31,6351 GLENHILLS WAY,6,6C,1422,ACCIDENTAL FIRES/ARSON -I RPT,7000,38.511446,-121.419015
6077,1/25/06 20:30,37TH ST / 4TH AVE,6,6A,1014,11377(A)HS POSS AMPHETAMINES,3572,38.549900,-121.466254
4411,1/19/06 6:16,STOCKTON BLVD / BROADWAY,6,6A,1007,TOWED/STORED VEHICLE,7000,38.546756,-121.453840
2324,1/10/06 23:00,6300 POWER INN RD,6,6C,1424,211 PC ROBBERY- BUSINESS,1299,38.510847,-121.409591
6086,1/25/06 21:30,12TH AVE / 36TH ST,6,6A,1041,529 PC FALSE PERSONATION,2604,38.541163,-121.467627
6088,1/25/06 21:43,2924 38TH ST,6,6A,1014,NARCOTICS SUSP/EVID/ACT- I RPT,7000,38.549045,-121.464879
2326,1/10/06 23:00,4241 V ST,6,6B,1004,SUSP PERS-NO CRIME - I RPT,7000,38.556197,-121.455184
1114,1/5/06 19:43,3300 12TH AVE,6,6A,1051,11350(A)HS POSS CNTRL SUBST,3532,38.540972,-121.470827
6092,1/25/06 22:00,3224 44TH ST,6,6A,1034,10851(A)VC TAKE VEH W/O OWNER,2404,38.544858,-121.456057
1110,1/5/06 19:26,6001 RIZA AVE,6,6C,1441,HARASSMENT - I RPT,7000,38.505537,-121.435739
1109,1/5/06 19:18,6305 PANTANO DR,6,6C,1422,459 PC BURGLARY RESIDENCE,2204,38.512071,-121.423148
2331,1/10/06 23:34,2710 39TH ST,6,6A,1014,TOWED/STORED VEHICLE,7000,38.550786,-121.463097
2312,1/10/06 21:40,2ND AVE / BROADWAY,6,6A,1012,647(B) PC PROSTITUTION,4004,38.553173,-121.469877
2311,1/10/06 21:30,5520 STANDISH RD,6,6C,1152,10851(A)VC TAKE VEH W/O OWNER,2404,38.525670,-121.416235
6010,1/25/06 15:30,5750 VELMA WAY,6,6B,1401,459 PC BURGLARY RESIDENCE,2204,38.522250,-121.438714
6055,1/25/06 19:00,2150 STOCKTON BLVD,6,6B,1003,CASUALTY REPORT,7000,38.557278,-121.461432
6014,1/25/06 15:42,34TH ST / BROADWAY,6,6A,1013,TOWED/STORED VEH-14602.6,7000,38.552708,-121.469478
6018,1/25/06 16:15,6600 RANCHO MADERA WAY,6,6C,1443,10851(A)VC TAKE VEH W/O OWNER,2404,38.507131,-121.424320
4441,1/19/06 9:26,7260 LEMON HILL AVE,6,6C,1422,CASUALTY REPORT,7000,38.515989,-121.420310
...,...,...,...,...,...,...,...,...,...
5471,1/23/06 13:45,5626 POP BECKER ST,1,1A,106,487(A) PC GRAND THEFT,2303,38.676969,-121.502227
6677,1/28/06 2:00,2441 NORBERT WAY,1,1C,447,10851(A)VC TAKE VEH W/O OWNER,2404,38.611561,-121.482126
6679,1/28/06 2:30,2112 BLACKRIDGE AVE,1,1A,136,487(A) GRAND THEFT-AUTO PARTS,2304,38.663940,-121.506223
1552,1/7/06 15:30,TRUXEL RD / GATEWAY PARK BLVD,1,1A,338,TOWED/STORED VEHICLE,7000,38.637479,-121.503896
2386,1/11/06 8:00,2611 ERIN DR,1,1B,435,MISSING PERSON,7000,38.613445,-121.489014
3620,1/16/06 1:00,1948 OAK BLUFF WAY,1,1B,423,594(B)(2)(A)VANDALISM GRAF-400,2999,38.620755,-121.503505
2887,1/12/06 21:00,6 INCA CT,1,1C,428,10851(A)VC TAKE VEH W/O OWNER,2404,38.619235,-121.481261
1565,1/7/06 17:00,4500 TRUXEL RD,1,1A,306,459 PC BURGLARY VEHICLE,2299,38.653572,-121.509513
632,1/3/06 21:30,3379 PAUMANOK WAY,1,1A,102,459 PC BURGLARY RESIDENCE,2204,38.677449,-121.536542
6693,1/28/06 3:30,2700 DEL PASO RD,1,1A,305,487(A) PC GRAND THEFT-SHOPLIFT,2303,38.655435,-121.522376
6694,1/28/06 3:49,W EL CAMINO AVE / GATEWAY OAKS DR,1,1B,421,TOWED/STORED VEHICLE,7000,38.614370,-121.517143
2385,1/11/06 8:00,1620 W EL CAMINO AVE,1,1B,443,TELEPEST -I RPT,7000,38.612664,-121.498815
2889,1/12/06 21:00,3201 AZEVEDO DR,1,1B,410,10851(A)VC TAKE VEH W/O OWNER,2404,38.625042,-121.510297
6700,1/28/06 5:20,5350 DUNLAY DR,1,1A,104,459 PC BURGLARY BUSINESS,2203,38.672327,-121.513576
6724,1/28/06 9:00,3301 ARENA BLVD,1,1A,303,484 PETTY THEFT/LICENSE PLATE,2399,38.643788,-121.534159
3613,1/16/06 0:01,1921 OAK BLUFF WAY,1,1B,423,484 PC PETTY THEFT,2399,38.620346,-121.504936
2891,1/12/06 21:00,291 MENARD CIR,1,1A,136,BOMBS/THREATS/EXPLOSIV- I RPT,7000,38.664908,-121.497572
6705,1/28/06 6:15,TRUXEL RD / VALLARTA CIR,1,1B,404,211 PC ROBBERY UNSPECIFIED,1299,38.629111,-121.497905
2895,1/12/06 21:15,ARENA BLVD / E COMMERCE WAY,1,1A,305,20001(A) VC HIT/RUN INJ/DEATH,5401,38.642998,-121.519435
5449,1/23/06 12:00,2226 GATEWAY OAKS DR,1,1B,440,487(A) PC GRAND THEFT,2303,38.607512,-121.516010
5448,1/23/06 12:00,1871 CLAYTON WAY,1,1A,136,653M(A) PC OBSCENE/THREAT CALL,5309,38.658372,-121.501859
621,1/3/06 20:19,2319 MARINA GLEN WAY,1,1B,473,10851(A)VC TAKE VEH W/O OWNER,2404,38.603762,-121.539929
2384,1/11/06 7:51,ARENA BLVD / EL CENTRO RD,1,1A,303,TOWED/STORED VEHICLE,7000,38.643028,-121.539686
4308,1/18/06 18:00,3403 WINTER PARK DR,1,1B,401,10852 VC VEHICLE TAMPERING,2999,38.629272,-121.504565
6715,1/28/06 8:00,1577 GARDEN HWY,1,1B,451,459 PC BURGLARY VEHICLE,2299,38.604684,-121.522713
617,1/3/06 19:58,935 RANCHO ROBLE WAY,1,1C,405,MISCELLANEOUS I RPT (ZMISC),7000,38.631946,-121.482611
5443,1/23/06 11:44,3301 FONG RANCH RD,1,1B,404,BATTERY - I RPT,7000,38.630207,-121.496000
615,1/3/06 19:52,4900 NATOMAS BLVD,1,1A,145,459 PC BURGLARY RESIDENCE,2204,38.662605,-121.508008
1579,1/7/06 18:00,2614 ERIN DR,1,1C,436,10851(A)VC TAKE VEH W/O OWNER,2404,38.613981,-121.488614
6138,1/26/06 6:00,5100 ALDERBERRY WAY,1,1A,113,484 PETTY THEFT/LICENSE PLATE,2399,38.668354,-121.521502

In [ ]:
df2=pd.read_csv("d:\\annual.csv")

In [ ]:
df2.sort_values('Year',ascending=False)

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2019,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,"728,239",ANZSIC06 divisions A-S (excluding classes K633...
3043,2019,Level 3,JJ11,Information Media Services,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,"2,310","ANZSIC06 groups J541, J542, J551, J552, J561, ..."
3095,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H12,Salaries and wages paid,Financial performance,"6,412",ANZSIC06 division K
3094,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H11,Depreciation,Financial performance,997,ANZSIC06 division K
3093,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H10,Indirect taxes,Financial performance,116,ANZSIC06 division K
3092,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H09,Interest and donations,Financial performance,"21,211",ANZSIC06 division K
3091,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H08,Total expenditure,Financial performance,"50,335",ANZSIC06 division K
3090,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H07,Non-operating income,Financial performance,"9,913",ANZSIC06 division K
3089,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,14,ANZSIC06 division K
3088,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,"51,860",ANZSIC06 division K
3087,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H04,Sales of goods and services,Financial performance,"22,836",ANZSIC06 division K
3086,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H01,Total income,Financial performance,"84,623",ANZSIC06 division K
3085,2019,Level 3,JJ12,"Telecommunications, Internet and Library Services",Percentage,H41,Liabilities structure,Financial ratios,35,"ANZSIC06 groups J580, J591, J592, J601, and J602"
3084,2019,Level 3,JJ12,"Telecommunications, Internet and Library Services",Percentage,H40,Return on total assets,Financial ratios,4,"ANZSIC06 groups J580, J591, J592, J601, and J602"
3083,2019,Level 3,JJ12,"Telecommunications, Internet and Library Services",Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups J580, J591, J592, J601, and J602"
3082,2019,Level 3,JJ12,"Telecommunications, Internet and Library Services",Percentage,H37,Quick ratio,Financial ratios,90,"ANZSIC06 groups J580, J591, J592, J601, and J602"
3081,2019,Level 3,JJ12,"Telecommunications, Internet and Library Services",Percentage,H36,Current ratio,Financial ratios,94,"ANZSIC06 groups J580, J591, J592, J601, and J602"
3096,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H13,Redundancy and severance,Financial performance,43,ANZSIC06 division K
3097,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H14,Salaries and wages to self employed commission...,Financial performance,564,ANZSIC06 division K
3098,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H19,Purchases and other operating expenses,Financial performance,"17,196",ANZSIC06 division K
3107,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H28,Disposals of fixed assets,Financial position,"3,357",ANZSIC06 division K
3113,2019,Level 1,KK,Financial and Insurance Services,Dollars,H34,Total income per employee count,Financial ratios,"1,325,400",ANZSIC06 division K
3112,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H33,Other liabilities,Financial position,"383,903",ANZSIC06 division K
3111,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H32,Current liabilities,Financial position,"550,207",ANZSIC06 division K
3110,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,"292,562",ANZSIC06 division K
3109,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H30,Total equity and liabilities,Financial position,"1,226,672",ANZSIC06 division K
3108,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H29,Other assets,Financial position,"858,268",ANZSIC06 division K
3106,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H27,Additions to fixed assets,Financial position,"6,375",ANZSIC06 division K
3099,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H20,Non-operating expenses,Financial performance,"3,838",ANZSIC06 division K
3105,2019,Level 1,KK,Financial and Insurance Services,Dollars (millions),H26,Fixed tangible assets,Financial position,"27,299",ANZSIC06 division K
...,...,...,...,...,...,...,...,...,...,...
29342,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H01,Total income,Financial performance,3656,"ANZSIC06 groups C245, C246, and C249"
29341,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Percentage,H41,Liabilities structure,Financial ratios,34,"ANZSIC06 groups C241, C242, C243, and C244"
29340,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C241, C242, C243, and C244"
29338,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,39,"ANZSIC06 groups C241, C242, C243, and C244"
29347,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H07,Non-operating income,Financial performance,24,"ANZSIC06 groups C245, C246, and C249"
29337,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Percentage,H37,Quick ratio,Financial ratios,80,"ANZSIC06 groups C241, C242, C243, and C244"
29336,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Percentage,H36,Current ratio,Financial ratios,110,"ANZSIC06 groups C241, C242, C243, and C244"
29335,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,14100,"ANZSIC06 groups C241, C242, C243, and C244"
29334,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Dollars,H34,Total income per employee count,Financial ratios,292900,"ANZSIC06 groups C241, C242, C243, and C244"
29333,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Dollars (millions),H33,Other liabilities,Financial position,823,"ANZSIC06 groups C241, C242, C243, and C244"
29332,2013,Level 4,CC821,Electronic and Electrical Equipment Manufacturing,Dollars (millions),H32,Current liabilities,Financial position,1462,"ANZSIC06 groups C241, C242, C243, and C244"
29346,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,8,"ANZSIC06 groups C245, C246, and C249"
29348,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H08,Total expenditure,Financial performance,3377,"ANZSIC06 groups C245, C246, and C249"
29364,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H28,Disposals of fixed assets,Financial position,53,"ANZSIC06 groups C245, C246, and C249"
29357,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H21,Opening stocks,Financial performance,449,"ANZSIC06 groups C245, C246, and C249"
29363,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H27,Additions to fixed assets,Financial position,123,"ANZSIC06 groups C245, C246, and C249"
29362,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H26,Fixed tangible assets,Financial position,516,"ANZSIC06 groups C245, C246, and C249"
29361,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H25,Current assets,Financial position,1483,"ANZSIC06 groups C245, C246, and C249"
29360,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H24,Total assets,Financial position,2401,"ANZSIC06 groups C245, C246, and C249"
29359,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H23,Surplus before income tax,Financial performance,298,"ANZSIC06 groups C245, C246, and C249"
29358,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H22,Closing stocks,Financial performance,469,"ANZSIC06 groups C245, C246, and C249"
29356,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H20,Non-operating expenses,Financial performance,59,"ANZSIC06 groups C245, C246, and C249"
29349,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H09,Interest and donations,Financial performance,36,"ANZSIC06 groups C245, C246, and C249"
29355,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H18,Other purchases and operating expenses,Financial performance,2012,"ANZSIC06 groups C245, C246, and C249"
29354,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H17,Purchases of goods bought for resale,Financial performance,281,"ANZSIC06 groups C245, C246, and C249"
29353,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H13,Redundancy and severance,Financial performance,1,"ANZSIC06 groups C245, C246, and C249"
29352,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H12,Salaries and wages paid,Financial performance,908,"ANZSIC06 groups C245, C246, and C249"
29351,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H11,Depreciation,Financial performance,72,"ANZSIC06 groups C245, C246, and C249"
29350,2013,Level 4,CC822,Machinery Manufacturing,Dollars (millions),H10,Indirect taxes,Financial performance,9,"ANZSIC06 groups C245, C246, and C249"
32444,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [ ]:
df2.sort_values(['Year','Value'])

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
28662,2013,Level 3,CC41,Printing,Percentage,H40,Return on total assets,Financial ratios,-1,ANZSIC06 groups C161 and C162
28698,2013,Level 4,CC411,Printing,Percentage,H40,Return on total assets,Financial ratios,-1,ANZSIC06 groups C161 and C162
29083,2013,Level 3,CC71,Primary Metal and Metal Product Manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,-131300,"ANZSIC06 groups C211, C212, C213, and C214"
29119,2013,Level 4,CC711,Primary Metal and Metal Product Manufacturing,Dollars,H35,Surplus per employee count,Financial ratios,-131300,"ANZSIC06 groups C211, C212, C213, and C214"
28589,2013,Level 3,CC32,"Pulp, Paper and Converted Paper Product Manufa...",Percentage,H39,Return on equity,Financial ratios,-17,ANZSIC06 groups C151 and C152
28625,2013,Level 4,CC321,"Pulp, Paper and Converted Paper Product Manufa...",Percentage,H39,Return on equity,Financial ratios,-17,ANZSIC06 groups C151 and C152
28645,2013,Level 3,CC41,Printing,Dollars (millions),H23,Surplus before income tax,Financial performance,-19,ANZSIC06 groups C161 and C162
28681,2013,Level 4,CC411,Printing,Dollars (millions),H23,Surplus before income tax,Financial performance,-19,ANZSIC06 groups C161 and C162
30097,2013,Level 4,FF116,Commission Based Wholesaling,Percentage,H38,Margin on sales of goods for resale,Financial ratios,-2,ANZSIC06 Group F380
29088,2013,Level 3,CC71,Primary Metal and Metal Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,-22,"ANZSIC06 groups C211, C212, C213, and C214"
29124,2013,Level 4,CC711,Primary Metal and Metal Product Manufacturing,Percentage,H40,Return on total assets,Financial ratios,-22,"ANZSIC06 groups C211, C212, C213, and C214"
28657,2013,Level 3,CC41,Printing,Dollars,H35,Surplus per employee count,Financial ratios,-2200,ANZSIC06 groups C161 and C162
28693,2013,Level 4,CC411,Printing,Dollars,H35,Surplus per employee count,Financial ratios,-2200,ANZSIC06 groups C161 and C162
28573,2013,Level 3,CC32,"Pulp, Paper and Converted Paper Product Manufa...",Dollars (millions),H23,Surplus before income tax,Financial performance,-229,ANZSIC06 groups C151 and C152
28609,2013,Level 4,CC321,"Pulp, Paper and Converted Paper Product Manufa...",Dollars (millions),H23,Surplus before income tax,Financial performance,-229,ANZSIC06 groups C151 and C152
28585,2013,Level 3,CC32,"Pulp, Paper and Converted Paper Product Manufa...",Dollars,H35,Surplus per employee count,Financial ratios,-44500,ANZSIC06 groups C151 and C152
28621,2013,Level 4,CC321,"Pulp, Paper and Converted Paper Product Manufa...",Dollars,H35,Surplus per employee count,Financial ratios,-44500,ANZSIC06 groups C151 and C152
28661,2013,Level 3,CC41,Printing,Percentage,H39,Return on equity,Financial ratios,-5,ANZSIC06 groups C161 and C162
28697,2013,Level 4,CC411,Printing,Percentage,H39,Return on equity,Financial ratios,-5,ANZSIC06 groups C161 and C162
29087,2013,Level 3,CC71,Primary Metal and Metal Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,-50,"ANZSIC06 groups C211, C212, C213, and C214"
29123,2013,Level 4,CC711,Primary Metal and Metal Product Manufacturing,Percentage,H39,Return on equity,Financial ratios,-50,"ANZSIC06 groups C211, C212, C213, and C214"
29071,2013,Level 3,CC71,Primary Metal and Metal Product Manufacturing,Dollars (millions),H23,Surplus before income tax,Financial performance,-644,"ANZSIC06 groups C211, C212, C213, and C214"
29107,2013,Level 4,CC711,Primary Metal and Metal Product Manufacturing,Dollars (millions),H23,Surplus before income tax,Financial performance,-644,"ANZSIC06 groups C211, C212, C213, and C214"
28590,2013,Level 3,CC32,"Pulp, Paper and Converted Paper Product Manufa...",Percentage,H40,Return on total assets,Financial ratios,-9,ANZSIC06 groups C151 and C152
28626,2013,Level 4,CC321,"Pulp, Paper and Converted Paper Product Manufa...",Percentage,H40,Return on total assets,Financial ratios,-9,ANZSIC06 groups C151 and C152
27851,2013,Level 1,AA,"Agriculture, Forestry and Fishing",Dollars (millions),H13,Redundancy and severance,Financial performance,0,ANZSIC06 division A
27881,2013,Level 3,AA11,Horticulture and Fruit Growing,Dollars (millions),H13,Redundancy and severance,Financial performance,0,"ANZSIC06 groups A011, A012, and A013"
27911,2013,Level 4,AA111,Horticulture and Fruit Growing,Dollars (millions),H13,Redundancy and severance,Financial performance,0,"ANZSIC06 groups A011, A012, and A013"
27941,2013,Level 3,AA12,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H13,Redundancy and severance,Financial performance,0,ANZSIC06 groups A014 and A015
27971,2013,Level 4,AA121,"Sheep, Beef Cattle and Grain Farming",Dollars (millions),H13,Redundancy and severance,Financial performance,0,ANZSIC06 groups A014 and A015
...,...,...,...,...,...,...,...,...,...,...
3951,2019,Level 1,OO,"Public Order, Safety and Regulatory Services",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,C,"ANZSIC06 division O (excluding classes O751, O..."
3952,2019,Level 1,OO,"Public Order, Safety and Regulatory Services",Dollars (millions),H07,Non-operating income,Financial performance,C,"ANZSIC06 division O (excluding classes O751, O..."
3982,2019,Level 3,OO21,"Public Order, Safety and Regulatory Services",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,C,ANZSIC06 groups O771 and O772 (excluding class...
3983,2019,Level 3,OO21,"Public Order, Safety and Regulatory Services",Dollars (millions),H07,Non-operating income,Financial performance,C,ANZSIC06 groups O771 and O772 (excluding class...
4013,2019,Level 4,OO213,"Public Order, Safety and Regulatory Services",Dollars (millions),H06,"Government funding, grants and subsidies",Financial performance,C,ANZSIC06 groups O771 and O772 (excluding class...
4014,2019,Level 4,OO213,"Public Order, Safety and Regulatory Services",Dollars (millions),H07,Non-operating income,Financial performance,C,ANZSIC06 groups O771 and O772 (excluding class...
4380,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H09,Interest and donations,Financial performance,C,"ANZSIC06 groups R891, R892, and R900"
4386,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H20,Non-operating expenses,Financial performance,C,"ANZSIC06 groups R891, R892, and R900"
4391,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H25,Current assets,Financial position,C,"ANZSIC06 groups R891, R892, and R900"
4395,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H29,Other assets,Financial position,C,"ANZSIC06 groups R891, R892, and R900"
4397,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,C,"ANZSIC06 groups R891, R892, and R900"
4398,2019,Level 4,RS111,Heritage and Artistic Activities,Dollars (millions),H32,Current liabilities,Financial position,C,"ANZSIC06 groups R891, R892, and R900"
4402,2019,Level 4,RS111,Heritage and Artistic Activities,Percentage,H36,Current ratio,Financial ratios,C,"ANZSIC06 groups R891, R892, and R900"
4403,2019,Level 4,RS111,Heritage and Artistic Activities,Percentage,H37,Quick ratio,Financial ratios,C,"ANZSIC06 groups R891, R892, and R900"
4404,2019,Level 4,RS111,Heritage and Artistic Activities,Percentage,H39,Return on equity,Financial ratios,C,"ANZSIC06 groups R891, R892, and R900"
4406,2019,Level 4,RS111,Heritage and Artistic Activities,Percentage,H41,Liabilities structure,Financial ratios,C,"ANZSIC06 groups R891, R892, and R900"
4416,2019,Level 4,RS112,Sport and Recreation Activities,Dollars (millions),H13,Redundancy and severance,Financial performance,C,"ANZSIC06 groups R911, R912, and R913"
4444,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H09,Interest and donations,Financial performance,C,ANZSIC06 group R920
4448,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H13,Redundancy and severance,Financial performance,C,ANZSIC06 group R920
4450,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H20,Non-operating expenses,Financial performance,C,ANZSIC06 group R920
4455,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H25,Current assets,Financial position,C,ANZSIC06 group R920
4459,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H29,Other assets,Financial position,C,ANZSIC06 group R920
4461,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H31,Shareholders funds or owners equity,Financial position,C,ANZSIC06 group R920
4462,2019,Level 4,RS113,Gambling Activities,Dollars (millions),H32,Current liabilities,Financial position,C,ANZSIC06 group R920
4466,2019,Level 4,RS113,Gambling Activities,Percentage,H36,Current ratio,Financial ratios,C,ANZSIC06 group R920
4467,2019,Level 4,RS113,Gambling Activities,Percentage,H37,Quick ratio,Financial ratios,C,ANZSIC06 group R920
4468,2019,Level 4,RS113,Gambling Activities,Percentage,H39,Return on equity,Financial ratios,C,ANZSIC06 group R920
4470,2019,Level 4,RS113,Gambling Activities,Percentage,H41,Liabilities structure,Financial ratios,C,ANZSIC06 group R920
3537,2019,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H27,Additions to fixed assets,Financial position,S,ANZSIC06 class L671200
3538,2019,Level 4,LL122,Non-Residential Property Operation,Dollars (millions),H28,Disposals of fixed assets,Financial position,S,ANZSIC06 class L671200

In [ ]:
df2['Variable_code'].value_counts()

H40    973
H05    973
H12    973
H21    973
H07    973
H41    973
H24    973
H09    973
H10    973
H20    973
H39    973
H22    973
H08    973
H01    973
H11    973
H31    973
H13    973
H23    973
H30    973
H36    938
H33    938
H37    938
H25    938
H26    938
H29    938
H32    938
H35    889
H34    889
H28    840
H06    840
H27    840
H19    609
H04    546
H02    364
H03    364
H38    364
H18    364
H17    364
H14    119
Name: Variable_code, dtype: int64

In [ ]:
a=df1['grid'].head()
a

0    1115
1    1512
2     212
3    1443
4     508
Name: grid, dtype: int64

In [ ]:
a.astype(float)

0    1115.0
1    1512.0
2     212.0
3    1443.0
4     508.0
Name: grid, dtype: float64

In [ ]:
df1

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
0,1/1/06 0:00,3108 OCCIDENTAL DR,3,3C,1115,10851(A)VC TAKE VEH W/O OWNER,2404,38.550420,-121.391416
1,1/1/06 0:00,2082 EXPEDITION WAY,5,5A,1512,459 PC BURGLARY RESIDENCE,2204,38.473501,-121.490186
2,1/1/06 0:00,4 PALEN CT,2,2A,212,10851(A)VC TAKE VEH W/O OWNER,2404,38.657846,-121.462101
3,1/1/06 0:00,22 BECKFORD CT,6,6C,1443,476 PC PASS FICTICIOUS CHECK,2501,38.506774,-121.426951
4,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY-UNSPECIFIED,2299,38.637448,-121.384613
5,1/1/06 0:00,5301 BONNIEMAE WAY,6,6B,1084,530.5 PC USE PERSONAL ID INFO,2604,38.526979,-121.451338
6,1/1/06 0:00,2217 16TH AVE,4,4A,957,459 PC BURGLARY VEHICLE,2299,38.537173,-121.487577
7,1/1/06 0:00,3547 P ST,3,3C,853,484 PC PETTY THEFT/INSIDE,2308,38.564335,-121.461883
8,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY BUSINESS,2203,38.637448,-121.384613
9,1/1/06 0:00,1326 HELMSMAN WAY,1,1B,444,1708 US THEFT OF MAIL,2310,38.609602,-121.491838
10,1/1/06 0:00,2315 STOCKTON BLVD,6,6B,1005,ASSAULT WITH WEAPON - I RPT,7000,38.554264,-121.454604
11,1/1/06 0:00,5112 63RD ST,6,6B,1088,530.5 PC USE PERSONAL ID INFO,2604,38.528165,-121.431453
12,1/1/06 0:00,6351 DRIFTWOOD ST,4,4C,1261,SUSP PERS-NO CRIME - I RPT,7000,38.510922,-121.548820
13,1/1/06 0:00,7721 COLLEGE TOWN DR,3,3C,888,530.5 PC USE PERSONAL ID INFO,2604,38.556115,-121.414273
14,1/1/06 0:00,8460 ROVANA CIR,6,6C,1447,484G(B) PC ACCESS CARD FRAUD,2605,38.503981,-121.392399
15,1/1/06 0:00,4856 11TH AVE,6,6B,1054,487(A) PC GRAND THEFT,2303,38.541529,-121.449510
16,1/1/06 0:00,6033 69TH ST,6,6C,1403,TELEPEST -I RPT,7000,38.516573,-121.423475
17,1/1/06 0:00,547 L ST,3,3M,742,487(A) GRAND THEFT-INSIDE,2308,38.581846,-121.501166
18,1/1/06 0:00,3525 42ND ST,6,6A,1034,530.5 PC USE PERSONAL ID INFO,2604,38.542708,-121.457207
19,1/1/06 0:00,5641 DORSET WAY,4,4C,1225,484J PC PUBLISH CARD INFO,2605,38.524600,-121.520361
20,1/1/06 0:01,5551 REXLEIGH CT,5,5C,1661,459 PC BURGLARY VEHICLE,2299,38.446592,-121.442378
21,1/1/06 0:01,1896 ARDEN WAY,2,2C,628,484G(B) PC ACCESS CARD FRAUD,2605,38.596642,-121.423349
22,1/1/06 0:01,6168 RIVERSIDE BLVD,4,4C,1251,484 PC PETTY THEFT,2399,38.515124,-121.529103
23,1/1/06 0:01,415 SEXTANT WAY,2,2A,213,459 PC BURGLARY VEHICLE,2299,38.656601,-121.456045
24,1/1/06 0:01,15 BASIN CT,5,5C,1654,TRAFFIC - I RPT,7000,38.442815,-121.409524
25,1/1/06 0:01,3340 62ND ST,6,6B,1047,594(B)(1)PC VANDALISM +$400,2999,38.543804,-121.433283
26,1/1/06 0:01,4280 DEER HILL DR,5,5B,1616,484G(B) PC ACCESS CARD FRAUD,2605,38.471219,-121.454739
27,1/1/06 0:01,2814 5TH ST,4,4A,923,484 PC PETTY THEFT/ OUTSIDE,2309,38.556452,-121.512331
28,1/1/06 0:01,1816 FLORIN RD,5,5A,1361,HARASSMENT - I RPT,7000,38.495353,-121.496560
29,1/1/06 0:01,1260 BELL AVE,2,2A,235,484 PC PETTY THEFT,2399,38.647174,-121.437517
...,...,...,...,...,...,...,...,...,...
7554,1/31/06 21:42,6125 STOCKTON BLVD,6,6B,1421,368(C) CAUSE PAIN/INJ TO ELDER,1315,38.515466,-121.436251
7555,1/31/06 21:50,6645 VALLEY HI DR,5,5C,1623,243(E)1 BATTERY NONCOHAB SPOUS,1315,38.471855,-121.428862
7556,1/31/06 21:52,DIXIEANNE AVE / ERICKSON ST,2,2C,604,10851(A)VC TAKE VEH W/O OWNER,2404,38.609299,-121.445035
7557,1/31/06 22:00,2400 DEL PASO BLVD,2,2B,564,11359 HS POSS FOR SALE MARIJ,3560,38.611410,-121.447654
7558,1/31/06 22:00,8689 CARLIN AVE,5,5C,1653,10851(A)VC TAKE VEH W/O OWNER,2404,38.443162,-121.434981
7559,1/31/06 22:00,23RD AVE / MARTIN LUTHER KING JR BLVD,6,6A,1081,10851(A)VC TAKE VEH W/O OWNER,2404,38.532135,-121.464702
7560,1/31/06 22:00,47TH ST / 14TH AVE,6,,1053,11378 HS POSS/SALE AMPHETAMINE,3571,38.539429,-121.451456
7561,1/31/06 22:00,BROADWAY / 42ND ST,6,6A,1015,647(B) PC PROSTITUTION,4004,38.546747,-121.457802
7562,1/31/06 22:04,13TH ST / G ST,3,3A,725,12020(A)1) PROHIBITED FIREARM,5212,38.582452,-121.487787
7563,1/31/06 22:09,34TH ST / TEMPLE AVE,6,6A,1051,11377(A)HS POSS AMPHETAMINES,3572,38.539180,-121.470547
7564,1/31/06 22:14,STOCKTON BLVD / ELDER CREEK RD,6,6C,1421,TRAFFIC-ACCIDENT-NON INJURY,5400,38.510505,-121.435864
7565,1/31/06 22:15,1225 48TH ST,3,3C,845,594(B)(2)(A) VANDALISM/ -$400,2999,38.564280,-121.444536
7566,1/31/06 22:20,1416 18TH ST,3,3B,766,594(B)(2)(A) VANDALISM/ -$400,2999,38.572365,-121.485030
7567,1/31/06 22:30,925 3RD ST,3,3M,732,537(A)(1) DEFRAUD INKEEP/-$400,2399,38.583309,-121.502418
7568,1/31/06 22:30,16TH ST / Q ST,3,3A,766,10851(A)VC TAKE VEH W/O OWNER,2404,38.570370,-121.488567
7569,1/31/06 22:30,34TH ST / 3RD AVE,6,6A,1022,647(B) PC PROSTITUTION,4004,38.551995,-121.469784
7570,1/31/06 22:30,1856 3RD AVE,4,4A,926,MISCELLANEOUS I RPT (ZMISC),7000,38.553461,-121.491734
7571,1/31/06 22:57,TAFT ST / EL CAMINO AVE,2,2C,564,TRAFFIC-ACCIDENT-NON INJURY,5400,38.611062,-121.438120
7572,1/31/06 23:00,X ST / 33RD ST,6,6A,1001,10851(A)VC TAKE VEH W/O OWNER,2404,38.556343,-121.469392
7573,1/31/06 23:00,3543 1ST AVE,6,6A,1013,459 PC BURGLARY VEHICLE,2299,38.553790,-121.466571
7574,1/31/06 23:00,3651 BRANCH ST,2,2A,513,459 PC BURGLARY VEHICLE,2299,38.634445,-121.444168
7575,1/31/06 23:00,1857 DISCOVERY WAY,6,6B,1006,484 PC PETTY THEFT/ OUTSIDE,2309,38.556651,-121.447707
7576,1/31/06 23:11,NATOMA WAY / ROANOKE AVE,2,2A,516,10853 VC MALIC MISCHIEF TO VEH,2999,38.634588,-121.422174
7577,1/31/06 23:27,7897 LA RIVIERA DR,3,3C,888,20002(A) HIT/RUN,5401,38.557901,-121.410635
7578,1/31/06 23:31,39TH ST / STOCKTON BLVD,6,6B,1005,CASUALTY REPORT,7000,38.556639,-121.459745
7579,1/31/06 23:36,26TH ST / G ST,3,3B,728,594(B)(2)(A) VANDALISM/ -$400,2999,38.577832,-121.470460
7580,1/31/06 23:40,4011 FREEPORT BLVD,4,4A,957,459 PC BURGLARY BUSINESS,2203,38.537591,-121.492591
7581,1/31/06 23:41,30TH ST / K ST,3,3C,841,TRAFFIC-ACCIDENT INJURY,5400,38.572030,-121.467012
7582,1/31/06 23:45,5303 FRANKLIN BLVD,4,4B,969,3056 PAROLE VIO - I RPT,7000,38.527187,-121.471248
7583,1/31/06 23:50,COBBLE COVE LN / COBBLE SHORES DR,4,4C,1294,TRAFFIC-ACCIDENT-NON INJURY,5400,38.479628,-121.528634

In [ ]:
df1['district'].replace(1,100).head(20)

0       3
1       5
2       2
3       6
4       2
5       6
6       4
7       3
8       2
9     100
10      6
11      6
12      4
13      3
14      6
15      6
16      6
17      3
18      6
19      4
Name: district, dtype: int64

In [ ]:
df2.isna().sum()

Year                           0
Industry_aggregation_NZSIOC    0
Industry_code_NZSIOC           0
Industry_name_NZSIOC           0
Units                          0
Variable_code                  0
Variable_name                  0
Variable_category              0
Value                          0
Industry_code_ANZSIC06         0
dtype: int64

In [ ]:
df3=pd.read_csv("d:\\COVIDclinicaltrials.csv")

In [ ]:
df3.isna().sum()

Rank                          0
NCT Number                    0
Title                         0
Acronym                    1378
Status                        0
Study Results                 0
Conditions                    0
Interventions               414
Outcome Measures             22
Sponsor/Collaborators         0
Gender                        5
Age                           0
Phases                     1127
Enrollment                   22
Funded Bys                    0
Study Type                    0
Study Designs                23
Other IDs                     1
Start Date                   22
Primary Completion Date      23
Completion Date              23
First Posted                  0
Results First Posted       2594
Last Update Posted            0
Locations                   418
Study Documents            2547
URL                           0
dtype: int64

In [ ]:
en=df3['Gender']

In [ ]:
en.unique()

array(['Female', 'All', 'change_value', 'Male'], dtype=object)

In [ ]:
en.replace(np.nan,'change_value',inplace=True)
en

0       Female
1          All
2          All
3          All
4          All
5          All
6          All
7          All
8          All
9          All
10         All
11         All
12      Female
13         All
14         All
15         All
16         All
17         All
18         All
19         All
20         All
21         All
22         All
23         All
24         All
25         All
26      Female
27         All
28         All
29         All
         ...
2565      Male
2566       All
2567       All
2568       All
2569       All
2570       All
2571      Male
2572      Male
2573       All
2574       All
2575       All
2576       All
2577       All
2578       All
2579       All
2580       All
2581       All
2582       All
2583      Male
2584    Female
2585       All
2586      Male
2587       All
2588       All
2589       All
2590    Female
2591       All
2592    Female
2593    Female
2594       All
Name: Gender, Length: 2595, dtype: object

In [ ]:
en.unique()

array(['Female', 'All', 'change_value', 'Male'], dtype=object)

In [ ]:
df3.isna().sum()

Rank                          0
NCT Number                    0
Title                         0
Acronym                    1378
Status                        0
Study Results                 0
Conditions                    0
Interventions               414
Outcome Measures             22
Sponsor/Collaborators         0
Gender                        0
Age                           0
Phases                     1127
Enrollment                   22
Funded Bys                    0
Study Type                    0
Study Designs                23
Other IDs                     1
Start Date                   22
Primary Completion Date      23
Completion Date              23
First Posted                  0
Results First Posted       2594
Last Update Posted            0
Locations                   418
Study Documents            2547
URL                           0
dtype: int64

In [ ]:
#b.replace(np.nan,"abc")

NameError: name 'b' is not defined

In [ ]:
df1.rename(columns={'district':'District_name'},inplace=True)

In [ ]:
df1

,cdatetime,address,District_name,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
0,1/1/06 0:00,3108 OCCIDENTAL DR,3,3C,1115,10851(A)VC TAKE VEH W/O OWNER,2404,38.550420,-121.391416
1,1/1/06 0:00,2082 EXPEDITION WAY,5,5A,1512,459 PC BURGLARY RESIDENCE,2204,38.473501,-121.490186
2,1/1/06 0:00,4 PALEN CT,2,2A,212,10851(A)VC TAKE VEH W/O OWNER,2404,38.657846,-121.462101
3,1/1/06 0:00,22 BECKFORD CT,6,6C,1443,476 PC PASS FICTICIOUS CHECK,2501,38.506774,-121.426951
4,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY-UNSPECIFIED,2299,38.637448,-121.384613
5,1/1/06 0:00,5301 BONNIEMAE WAY,6,6B,1084,530.5 PC USE PERSONAL ID INFO,2604,38.526979,-121.451338
6,1/1/06 0:00,2217 16TH AVE,4,4A,957,459 PC BURGLARY VEHICLE,2299,38.537173,-121.487577
7,1/1/06 0:00,3547 P ST,3,3C,853,484 PC PETTY THEFT/INSIDE,2308,38.564335,-121.461883
8,1/1/06 0:00,3421 AUBURN BLVD,2,2A,508,459 PC BURGLARY BUSINESS,2203,38.637448,-121.384613
9,1/1/06 0:00,1326 HELMSMAN WAY,1,1B,444,1708 US THEFT OF MAIL,2310,38.609602,-121.491838
10,1/1/06 0:00,2315 STOCKTON BLVD,6,6B,1005,ASSAULT WITH WEAPON - I RPT,7000,38.554264,-121.454604
11,1/1/06 0:00,5112 63RD ST,6,6B,1088,530.5 PC USE PERSONAL ID INFO,2604,38.528165,-121.431453
12,1/1/06 0:00,6351 DRIFTWOOD ST,4,4C,1261,SUSP PERS-NO CRIME - I RPT,7000,38.510922,-121.548820
13,1/1/06 0:00,7721 COLLEGE TOWN DR,3,3C,888,530.5 PC USE PERSONAL ID INFO,2604,38.556115,-121.414273
14,1/1/06 0:00,8460 ROVANA CIR,6,6C,1447,484G(B) PC ACCESS CARD FRAUD,2605,38.503981,-121.392399
15,1/1/06 0:00,4856 11TH AVE,6,6B,1054,487(A) PC GRAND THEFT,2303,38.541529,-121.449510
16,1/1/06 0:00,6033 69TH ST,6,6C,1403,TELEPEST -I RPT,7000,38.516573,-121.423475
17,1/1/06 0:00,547 L ST,3,3M,742,487(A) GRAND THEFT-INSIDE,2308,38.581846,-121.501166
18,1/1/06 0:00,3525 42ND ST,6,6A,1034,530.5 PC USE PERSONAL ID INFO,2604,38.542708,-121.457207
19,1/1/06 0:00,5641 DORSET WAY,4,4C,1225,484J PC PUBLISH CARD INFO,2605,38.524600,-121.520361
20,1/1/06 0:01,5551 REXLEIGH CT,5,5C,1661,459 PC BURGLARY VEHICLE,2299,38.446592,-121.442378
21,1/1/06 0:01,1896 ARDEN WAY,2,2C,628,484G(B) PC ACCESS CARD FRAUD,2605,38.596642,-121.423349
22,1/1/06 0:01,6168 RIVERSIDE BLVD,4,4C,1251,484 PC PETTY THEFT,2399,38.515124,-121.529103
23,1/1/06 0:01,415 SEXTANT WAY,2,2A,213,459 PC BURGLARY VEHICLE,2299,38.656601,-121.456045
24,1/1/06 0:01,15 BASIN CT,5,5C,1654,TRAFFIC - I RPT,7000,38.442815,-121.409524
25,1/1/06 0:01,3340 62ND ST,6,6B,1047,594(B)(1)PC VANDALISM +$400,2999,38.543804,-121.433283
26,1/1/06 0:01,4280 DEER HILL DR,5,5B,1616,484G(B) PC ACCESS CARD FRAUD,2605,38.471219,-121.454739
27,1/1/06 0:01,2814 5TH ST,4,4A,923,484 PC PETTY THEFT/ OUTSIDE,2309,38.556452,-121.512331
28,1/1/06 0:01,1816 FLORIN RD,5,5A,1361,HARASSMENT - I RPT,7000,38.495353,-121.496560
29,1/1/06 0:01,1260 BELL AVE,2,2A,235,484 PC PETTY THEFT,2399,38.647174,-121.437517
...,...,...,...,...,...,...,...,...,...
7554,1/31/06 21:42,6125 STOCKTON BLVD,6,6B,1421,368(C) CAUSE PAIN/INJ TO ELDER,1315,38.515466,-121.436251
7555,1/31/06 21:50,6645 VALLEY HI DR,5,5C,1623,243(E)1 BATTERY NONCOHAB SPOUS,1315,38.471855,-121.428862
7556,1/31/06 21:52,DIXIEANNE AVE / ERICKSON ST,2,2C,604,10851(A)VC TAKE VEH W/O OWNER,2404,38.609299,-121.445035
7557,1/31/06 22:00,2400 DEL PASO BLVD,2,2B,564,11359 HS POSS FOR SALE MARIJ,3560,38.611410,-121.447654
7558,1/31/06 22:00,8689 CARLIN AVE,5,5C,1653,10851(A)VC TAKE VEH W/O OWNER,2404,38.443162,-121.434981
7559,1/31/06 22:00,23RD AVE / MARTIN LUTHER KING JR BLVD,6,6A,1081,10851(A)VC TAKE VEH W/O OWNER,2404,38.532135,-121.464702
7560,1/31/06 22:00,47TH ST / 14TH AVE,6,,1053,11378 HS POSS/SALE AMPHETAMINE,3571,38.539429,-121.451456
7561,1/31/06 22:00,BROADWAY / 42ND ST,6,6A,1015,647(B) PC PROSTITUTION,4004,38.546747,-121.457802
7562,1/31/06 22:04,13TH ST / G ST,3,3A,725,12020(A)1) PROHIBITED FIREARM,5212,38.582452,-121.487787
7563,1/31/06 22:09,34TH ST / TEMPLE AVE,6,6A,1051,11377(A)HS POSS AMPHETAMINES,3572,38.539180,-121.470547
7564,1/31/06 22:14,STOCKTON BLVD / ELDER CREEK RD,6,6C,1421,TRAFFIC-ACCIDENT-NON INJURY,5400,38.510505,-121.435864
7565,1/31/06 22:15,1225 48TH ST,3,3C,845,594(B)(2)(A) VANDALISM/ -$400,2999,38.564280,-121.444536
7566,1/31/06 22:20,1416 18TH ST,3,3B,766,594(B)(2)(A) VANDALISM/ -$400,2999,38.572365,-121.485030
7567,1/31/06 22:30,925 3RD ST,3,3M,732,537(A)(1) DEFRAUD INKEEP/-$400,2399,38.583309,-121.502418
7568,1/31/06 22:30,16TH ST / Q ST,3,3A,766,10851(A)VC TAKE VEH W/O OWNER,2404,38.570370,-121.488567
7569,1/31/06 22:30,34TH ST / 3RD AVE,6,6A,1022,647(B) PC PROSTITUTION,4004,38.551995,-121.469784
7570,1/31/06 22:30,1856 3RD AVE,4,4A,926,MISCELLANEOUS I RPT (ZMISC),7000,38.553461,-121.491734
7571,1/31/06 22:57,TAFT ST / EL CAMINO AVE,2,2C,564,TRAFFIC-ACCIDENT-NON INJURY,5400,38.611062,-121.438120
7572,1/31/06 23:00,X ST / 33RD ST,6,6A,1001,10851(A)VC TAKE VEH W/O OWNER,2404,38.556343,-121.469392
7573,1/31/06 23:00,3543 1ST AVE,6,6A,1013,459 PC BURGLARY VEHICLE,2299,38.553790,-121.466571
7574,1/31/06 23:00,3651 BRANCH ST,2,2A,513,459 PC BURGLARY VEHICLE,2299,38.634445,-121.444168
7575,1/31/06 23:00,1857 DISCOVERY WAY,6,6B,1006,484 PC PETTY THEFT/ OUTSIDE,2309,38.556651,-121.447707
7576,1/31/06 23:11,NATOMA WAY / ROANOKE AVE,2,2A,516,10853 VC MALIC MISCHIEF TO VEH,2999,38.634588,-121.422174
7577,1/31/06 23:27,7897 LA RIVIERA DR,3,3C,888,20002(A) HIT/RUN,5401,38.557901,-121.410635
7578,1/31/06 23:31,39TH ST / STOCKTON BLVD,6,6B,1005,CASUALTY REPORT,7000,38.556639,-121.459745
7579,1/31/06 23:36,26TH ST / G ST,3,3B,728,594(B)(2)(A) VANDALISM/ -$400,2999,38.577832,-121.470460
7580,1/31/06 23:40,4011 FREEPORT BLVD,4,4A,957,459 PC BURGLARY BUSINESS,2203,38.537591,-121.492591
7581,1/31/06 23:41,30TH ST / K ST,3,3C,841,TRAFFIC-ACCIDENT INJURY,5400,38.572030,-121.467012
7582,1/31/06 23:45,5303 FRANKLIN BLVD,4,4B,969,3056 PAROLE VIO - I RPT,7000,38.527187,-121.471248
7583,1/31/06 23:50,COBBLE COVE LN / COBBLE SHORES DR,4,4C,1294,TRAFFIC-ACCIDENT-NON INJURY,5400,38.479628,-121.528634

In [ ]:
d1 = {"Name": ["Pankaj", "Lisa", "David"], "ID": [1, 2, 3], "Role": ["CEO", "Editor", "Author"]}
df3 = pd.DataFrame(d1)

d2 = {"Name": ["Pankaj"], "ID": [1], "Role": ["CEO"]}
df4=pd.DataFrame(d2)

In [ ]:
df3

     Name  ID    Role
0  Pankaj   1     CEO
1    Lisa   2  Editor
2   David   3  Author

In [ ]:
df4

     Name  ID Role
0  Pankaj   1  CEO

In [ ]:
df2=pd.concat([df3,df4],ignore_index=True)

In [ ]:
df2

     Name  ID    Role
0  Pankaj   1     CEO
1    Lisa   2  Editor
2   David   3  Author
3  Pankaj   1     CEO

In [ ]:
d3={"city":['Delhi','Noida','Aligarh','Agra']}
df4=pd.DataFrame(d3)

In [ ]:
df5=pd.concat([df2,df4],axis=1)

In [ ]:
df5

     Name  age  ID    Role     city
0  Pankaj   23   1     CEO    Delhi
1    Lisa   45   2  Editor    Noida
2   David   23   3  Author  Aligarh
3  Pankaj   56   1     CEO     Agra

In [ ]:
df5.insert(0,'age',[23,45,23,56])

ValueError: cannot insert age, already exists

In [ ]:
df5.insert(2,'age1',[23,45,23,56])

In [ ]:
df5

     Name  age  age1  ID    Role     city
0  Pankaj   23    23   1     CEO    Delhi
1    Lisa   45    45   2  Editor    Noida
2   David   23    23   3  Author  Aligarh
3  Pankaj   56    56   1     CEO     Agra

In [ ]:
df5.drop_duplicates(subset=['age'])

     Name  age  age1  ID    Role   city
0  Pankaj   23    23   1     CEO  Delhi
1    Lisa   45    45   2  Editor  Noida
3  Pankaj   56    56   1     CEO   Agra

In [ ]:
df5

     Name  age  age1  ID    Role     city
0  Pankaj   23    23   1     CEO    Delhi
1    Lisa   45    45   2  Editor    Noida
2   David   23    23   3  Author  Aligarh
3  Pankaj   56    56   1     CEO     Agra

In [ ]:
df2=pd.read_csv("d:\\SacramentocrimeJanuary2006.csv")

In [ ]:
df2.sample(n=100)

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
7040,1/29/06 21:00,838 RANCHO ROBLE WAY,1,1C,405,10851(A)VC TAKE VEH W/O OWNER,2404,38.630201,-121.482806
7288,1/30/06 19:08,4100 ASTORIA ST,2,2A,237,CHILD WELFARE - I RPT,7000,38.641872,-121.414951
5328,1/22/06 22:00,1689 ARDEN WAY,2,2C,619,10851 VC AUTO THEFT LOCATE,2404,38.601545,-121.427470
5780,1/24/06 16:52,1514A MCALLISTER AVE,4,4C,1311,10851 VC AUTO THEFT LOCATE,2404,38.514419,-121.501095
5116,1/21/06 22:17,1380 57TH ST,3,3C,846,BURGLARY - I RPT,7000,38.559492,-121.436788
4586,1/19/06 19:00,18TH ST / K ST,3,3M,746,459 PC BURGLARY VEHICLE,2299,38.576299,-121.483036
5139,1/22/06 0:00,3701 55TH ST,6,6B,1056,459 PC BURGLARY VEHICLE,2299,38.541030,-121.441025
6235,1/26/06 13:47,LOS ROBLES BLVD / MARYSVILLE BLVD,2,2B,526,10851 VC AUTO THEFT LOCATE,2404,38.628797,-121.431746
4418,1/19/06 7:46,130 PRAIRIE CIR,6,6C,1443,11350(B)HS POSSESS QUAALUDES,3582,38.509602,-121.417646
1906,1/9/06 9:00,720 9TH ST,3,3A,732,290(A)(1)(D) FAIL TO REG-5 DAY,3699,38.583576,-121.494290
2970,1/13/06 8:45,SEAMAS AVE / RIVERSIDE BLVD,4,4A,1203,TOWED/STORED VEHICLE,7000,38.525942,-121.522250
2232,1/10/06 16:00,GREENHAVEN DR / FLORIN RD,4,4C,1275,484 PC PETTY THEFT/ OUTSIDE,2309,38.495904,-121.523551
3554,1/15/06 19:00,3357 I ST,3,3C,832,10851(A)VC TAKE VEH W/O OWNER,2404,38.573073,-121.460834
3282,1/14/06 15:03,1701 ARDEN WAY,2,2C,619,484 PC PETTY THEFT,2399,38.600273,-121.425248
4277,1/18/06 16:29,4630 MARION CT,4,4A,956,594(B)(2)(A) VANDALISM/ -$400,2999,38.533255,-121.497723
6282,1/26/06 17:00,2790 21ST ST,4,4A,917,459 PC BURGLARY BUSINESS,2203,38.553177,-121.488277
6058,1/25/06 19:10,113 K ST,3,3M,741,484 PETTY THEFT-SHOPLIFT,2303,38.582454,-121.505275
5217,1/22/06 12:33,CENTER PKWY / COSUMNES RIVER BLVD,5,5C,1645,20001(A) VC HIT/RUN INJ/DEATH,5401,38.458142,-121.428371
1955,1/9/06 12:30,2715 EDINGER AVE,4,4B,1346,290(A)(1)(A) FAIL REG-CHG ADD,3699,38.503518,-121.475767
3414,1/15/06 1:38,2451 MEADOWVIEW RD,5,5A,1396,594(B)(2)(A) VANDALISM/ -$400,2999,38.481916,-121.479436
5091,1/21/06 20:15,16TH ST / BROADWAY,4,4A,906,242 PC BATTERY CIVILIAN,1313,38.561592,-121.492382
1755,1/8/06 17:00,4100 NORTHGATE BLVD,1,1C,309,459 PC BURGLARY VEHICLE,2299,38.643163,-121.474582
6648,1/28/06 0:01,1 DECATHLON CIR,5,5B,1614,THREATS - I RPT,7000,38.476238,-121.455867
3442,1/15/06 5:39,8441 SPECIALTY CIR,6,6C,1447,459 PC BURGLARY BUSINESS,2203,38.502351,-121.394771
3271,1/14/06 14:10,321 UNITY CIR,1,1B,478,THREATS - I RPT,7000,38.613741,-121.523006
913,1/5/06 0:01,3604 ASTORIA ST,2,2A,517,10851(A)VC TAKE VEH W/O OWNER,2404,38.632988,-121.415301
1567,1/7/06 17:00,1451 RIVER PARK DR,2,2C,626,459 PC BURGLARY VEHICLE,2299,38.598641,-121.439660
5191,1/22/06 7:48,28TH ST / I ST,3,3B,738,10851(A)VC TAKE VEH W/O OWNER,2404,38.574924,-121.468739
592,1/3/06 18:12,5741 63RD ST,6,6B,1402,459 PC BURGLARY RESIDENCE,2204,38.522983,-121.430729
5979,1/25/06 13:30,3RD ST / K ST,3,3M,742,594(B)(1)PC VANDALISM +$400,2999,38.581657,-121.503227
...,...,...,...,...,...,...,...,...,...
1297,1/6/06 15:15,950 FRIENZA AVE,2,2B,564,459 PC BURGLARY RESIDENCE,2204,38.612785,-121.444704
359,1/2/06 20:30,3348 DRY BRANCH CT,1,1B,401,10851(A)VC TAKE VEH W/O OWNER,2404,38.628756,-121.508511
1182,1/6/06 0:00,2500 SEAMIST DR,1,1B,444,TOWED/STORED VEHICLE,7000,38.612282,-121.493596
237,1/1/06 22:36,2ND ST / I ST,3,3M,731,243(D) PC BATT/CIVILIAN W/INJ,1315,38.584243,-121.503647
2911,1/12/06 23:22,3231 DEL MAR WAY,2,2B,545,5150 WI DANGER SELF/OTHERS,7000,38.627049,-121.435285
468,1/3/06 9:00,7060 ROCK CREEK WAY,6,6C,1422,530.5 PC USE PERSONAL ID INFO,2604,38.513640,-121.421192
7054,1/29/06 22:00,2400 DONNER WAY,4,4A,928,NON INJ HR/MAIL OUT REPORT,7000,38.547872,-121.482801
1782,1/8/06 19:37,3800 STOCKTON BLVD,6,6A,1053,243(D) PC BATT/CIVILIAN W/INJ,1315,38.540205,-121.450565
2136,1/10/06 7:30,815 19TH ST,3,3B,736,459 PC BURGLARY RESIDENCE,2204,38.578716,-121.480216
4899,1/20/06 22:07,MACK RD / BROOKFIELD DR,5,5B,1614,23103(A) RECKLESS ON HIGHWAY,5499,38.480937,-121.463010
403,1/3/06 0:01,5720 HOLSTEIN WAY,4,4C,1227,459 PC BURGLARY VEHICLE,2299,38.521870,-121.511697
3343,1/14/06 20:00,23 MARATHON CT,5,5B,1614,MISSING PERSON,7000,38.476740,-121.459846
109,1/1/06 8:00,3709 PRESIDIO ST,2,2A,516,LOST PROPERTY - I RPT,7000,38.635001,-121.421365
5526,1/23/06 17:57,1695 ARDEN WAY,2,2C,616,484 PC PETTY THEFT,2399,38.601762,-121.425827
2875,1/12/06 19:53,HOGAN DR / 24TH ST,4,4B,1336,3056 PAROLE VIO - I RPT,7000,38.509130,-121.483008
4396,1/19/06 0:21,MACK RD / TANGERINE AVE,5,5B,1604,23152(A) VC DUI-ALCOHOL/DRUGS,5404,38.474275,-121.446594
5064,1/21/06 18:30,3555 AUBURN BLVD,2,2A,509,MISSING PERSON,7000,38.638629,-121.381560
5434,1/23/06 11:00,5760 RIGHTWOOD WAY,5,5C,1644,459 PC BURGLARY RESIDENCE,2204,38.451861,-121.437085
105,1/1/06 7:55,398 FLORIN RD,4,4C,1259,211 PC ROBBERY- BUSINESS,1299,38.507671,-121.541275
6456,1/27/06 11:59,7575 RUSH RIVER DR,4,4C,1293,SUSPICIOUS VEHICLE - I RPT,7000,38.484472,-121.532051
1209,1/6/06 6:30,7804 CENTER PKWY,5,5B,1621,484 PETTY THEFT/LICENSE PLATE,2399,38.473906,-121.437914
7513,1/31/06 18:00,POTOMAC AVE / NATOMA ST,1,1C,419,FOUND PROPERTY - I RPT,7000,38.622015,-121.470058
566,1/3/06 16:45,166 STANFORD AVE,2,2C,601,23152(A) VC DUI-ALCOHOL/DRUGS,5404,38.608946,-121.462676
7512,1/31/06 18:00,312 KELLEY CT,2,2A,236,459 PC BURGLARY RESIDENCE,2204,38.643417,-121.425646
4594,1/19/06 19:50,7560 RUSH RIVER DR,4,4C,1292,HARASSMENT - I RPT,7000,38.484888,-121.535695
6060,1/25/06 19:20,8101 COSUMNES RIVER BLVD,5,5C,1639,487(A) PC GRAND THEFT-SHOPLIFT,2303,38.457182,-121.413341
2831,1/12/06 16:57,2711 21ST AVE,4,4B,958,10851 VC AUTO THEFT LOCATE,2404,38.534050,-121.477622
5972,1/25/06 13:05,3066 FREEPORT BLVD,4,4A,925,GANG ACTIVITY - I RPT,7000,38.548855,-121.490885
6379,1/27/06 0:10,N 12TH ST / N B ST,3,3A,709,243(D) PC BATT/CIVILIAN W/INJ,1315,38.590500,-121.485889
5102,1/21/06 20:55,3500 FOLSOM BLVD,3,3C,853,TOWED/STORED VEH-14602.6,7000,38.566177,-121.462554

In [ ]:
df2.sample(frac=0.20)

,cdatetime,address,district,beat,grid,crimedescr,ucr_ncic_code,latitude,longitude
4412,1/19/06 6:30,1121 COMMONS DR,3,3C,876,459 PC BURGLARY VEHICLE,2299,38.567152,-121.410601
4040,1/17/06 19:30,2925 CAMARILLO DR,1,1C,428,10851(A)VC TAKE VEH W/O OWNER,2404,38.619440,-121.479933
2103,1/10/06 0:01,3200 TRUXEL RD,1,1C,414,459 PC BURGLARY VEHICLE,2299,38.626486,-121.496695
1194,1/6/06 1:19,6220 BELLEAU WOOD LN,4,4C,1331,459 PC BURGLARY BUSINESS,2203,38.512752,-121.504881
2026,1/9/06 17:51,6 KLONDIKE CT,1,1A,136,11377(A)HS POSS AMPHETAMINES,3572,38.658778,-121.504318
6495,1/27/06 14:25,25TH ST / T ST,3,3B,778,TRAFFIC-ACCIDENT-NON INJURY,5400,38.563895,-121.477977
5908,1/25/06 9:00,1861 GLENROSE AVE,2,2C,567,10851(A)VC TAKE VEH W/O OWNER,2404,38.614999,-121.423449
1452,1/7/06 3:30,2 KELSO CIR,1,1C,416,243(E)1 BATTERY NONCOHAB SPOUS,1315,38.626773,-121.492678
3446,1/15/06 7:00,3418 JUMILLA WAY,1,1A,343,10851(A)VC TAKE VEH W/O OWNER,2404,38.628398,-121.537746
2887,1/12/06 21:00,6 INCA CT,1,1C,428,10851(A)VC TAKE VEH W/O OWNER,2404,38.619235,-121.481261
4836,1/20/06 17:40,5500 19TH AVE,6,6B,1065,10851 VC AUTO THEFT LOCATE,2404,38.534654,-121.441777
5285,1/22/06 18:33,16TH ST / C ST,3,3A,716,12020(A)1) PROHIBITED FIREARM,5212,38.585767,-121.481893
5633,1/24/06 7:59,FRANKLIN BLVD / 13TH AVE,4,4B,958,TOWED/STORED VEHICLE,7000,38.540313,-121.475566
1685,1/8/06 4:00,7308 FARM DALE WAY,4,4C,1289,594(B)(1)PC VANDALISM +$400,2999,38.492103,-121.507680
28,1/1/06 0:01,1816 FLORIN RD,5,5A,1361,HARASSMENT - I RPT,7000,38.495353,-121.496560
3772,1/16/06 20:17,1415 30TH ST,3,3C,851,10851(A)VC TAKE VEH W/O OWNER,2404,38.568207,-121.467985
6954,1/29/06 12:00,717 23RD ST,3,3B,727,MISSING PERSON,7000,38.578207,-121.474480
6036,1/25/06 17:37,16TH ST / I ST,3,3M,736,TRAFFIC-ACCIDENT-NON INJURY,5400,38.579198,-121.484743
6888,1/28/06 23:37,AZUSA ST / MORELL ST,1,1C,447,20002(A) HIT/RUN,5401,38.609117,-121.484054
6695,1/28/06 3:59,2028 ARGAIL WAY,4,4A,956,451(D) PC ARSON OF PROPERTY,2099,38.534375,-121.494397
5811,1/24/06 19:28,3049 CLAY ST,2,2B,545,FAMILY DISTURBANCE - I RPT,7000,38.623096,-121.439502
4478,1/19/06 12:16,6490 GLORIA DR,4,4C,1255,5150 WI DANGER SELF/OTHERS,7000,38.510365,-121.520935
181,1/1/06 16:51,2314 Q ST,3,3B,767,TRAFFIC-ACCIDENT-NON INJURY,5400,38.567380,-121.478651
2676,1/12/06 3:00,6670 ELVAS AVE,3,3C,847,459 PC BURGLARY VEHICLE,2299,38.553950,-121.425397
5024,1/21/06 14:25,HARRIS AVE / VERN ST,2,2A,511,TOWED/STORED VEHICLE,7000,38.638607,-121.454915
4759,1/20/06 12:00,4800 FRANKLIN BLVD,4,4B,969,LOST PROPERTY - I RPT,7000,38.531375,-121.473741
2735,1/12/06 10:30,BROOKFIELD DR / MACK RD,5,5B,1614,TRAFFIC-ACCIDENT-NON INJURY,5400,38.480937,-121.463010
2207,1/10/06 14:00,547 L ST,3,3M,742,HOMICIDE ASSAULT - I RPT,7000,38.581846,-121.501166
4264,1/18/06 15:30,24TH ST / W ST,3,3B,787,TRAFFIC-ACCIDENT INJURY,5400,38.560977,-121.480734
4132,1/18/06 8:00,4500 TYNEBOURNE ST,1,1A,304,CHILD CUSTODY - I RPT,7000,38.653336,-121.536314
...,...,...,...,...,...,...,...,...,...
459,1/3/06 8:43,7231 GREENHAVEN DR,4,4C,1287,SUSP PERS-NO CRIME - I RPT,7000,38.494180,-121.523539
6777,1/28/06 15:26,2700 32ND ST,6,6A,1011,11364 HS POSS DRUG PARAPH,3599,38.553495,-121.472319
4018,1/17/06 18:00,2751 WILMINGTON AVE,4,4B,958,487(A) PC GRAND THEFT,2303,38.538741,-121.477822
3412,1/15/06 1:31,715 L ST,3,3M,742,602(K)TRESPASS:INJURE PROPERTY,5707,38.579052,-121.497691
5616,1/24/06 5:02,4985 STOCKTON BLVD,6,6B,1086,594(B)(2)(A) VANDALISM/ -$400,2999,38.530466,-121.443352
2322,1/10/06 22:30,614 23RD ST,3,3B,727,459 PC BURGLARY RESIDENCE,2204,38.579668,-121.474560
1303,1/6/06 15:42,11TH ST / T ST,3,3A,774,TRAFFIC-ACCIDENT INJURY,5400,38.568941,-121.496905
1383,1/6/06 22:00,6 SOUTHBURY WAY,1,1A,113,594(B)(2)(A) VANDALISM/ -$400,2999,38.670873,-121.522963
5851,1/24/06 23:17,6868 PARK RIVIERA WAY,4,4C,1266,459 PC BURGLARY VEHICLE,2299,38.501584,-121.545636
316,1/2/06 16:00,1690 ARDEN WAY,2,2C,628,459 PC BURGLARY VEHICLE,2299,38.598085,-121.427554
7314,1/30/06 21:36,2717 D ST,3,3B,718,459 PC BURGLARY RESIDENCE,2204,38.580869,-121.466827
5245,1/22/06 15:00,6641 NARROWGAUGE WAY,5,5C,1635,MISSING PERSON,7000,38.460021,-121.425262
4368,1/18/06 22:00,7197 SNOWY BIRCH WAY,5,5C,1637,459 PC BURGLARY VEHICLE,2299,38.458865,-121.419118
4482,1/19/06 12:32,I ST / 24TH ST,3,3B,738,TOWED/STORED VEH-14602.6,7000,38.576352,-121.474084
2173,1/10/06 11:44,2562 TRACTION AVE,2,2B,563,10851 VC AUTO THEFT LOCATE,2404,38.613420,-121.452791
227,1/1/06 22:00,MCGLASHAN ST / PERRY AVE,6,6B,1084,20002(A) HIT/RUN,5401,38.531374,-121.450640
3135,1/13/06 19:56,5610 STOCKTON BLVD,6,6B,1401,211 PC ROBBERY- BUSINESS,1299,38.524395,-121.442857
7140,1/30/06 8:00,6021 WILKINSON ST,6,6C,1404,10851 VC AUTO THEFT LOCATE,2404,38.517560,-121.414271
3949,1/17/06 15:00,833 CALVADOS AVE,2,2C,603,10851 VC AUTO THEFT LOCATE,2404,38.607645,-121.447659
993,1/5/06 12:10,7612 TIERRA ARBOR WAY,6,6C,1445,459 PC BURGLARY RESIDENCE,2204,38.501968,-121.414843
206,1/1/06 19:00,2800 BROADWAY,4,4A,908,484 PC PETTY THEFT/INSIDE,2308,38.557014,-121.476272
4204,1/18/06 12:26,3700 2ND AVE,6,6A,1014,374.3(A) PC ILLEGAL DUMPING,7399,38.551691,-121.465226
1449,1/7/06 3:01,3208 10TH AVE,6,6A,1041,459 PC BURGLARY RESIDENCE,2204,38.542558,-121.472889
2961,1/13/06 8:00,2250 68TH AVE,5,5A,1384,242 PC BATTERY CIVILIAN,1313,38.489342,-121.485940
6299,1/26/06 18:08,D ST / 12TH ST,3,3A,715,529 PC FALSE PERSONATION,2604,38.586157,-121.487950
452,1/3/06 8:08,POCKET RD / COLEMAN RANCH WAY,4,4C,1294,TRAFFIC-ACCIDENT INJURY,5400,38.477041,-121.523125
975,1/5/06 11:00,902 DEL PASO BLVD,2,2C,612,GRAND THEFT - I RPT,7000,38.602195,-121.465870
6154,1/26/06 8:00,3500 FLORIN RD,5,5B,1367,MISSING PERSON,7000,38.494078,-121.467394
6052,1/25/06 18:45,3630 24TH AVE,6,6A,1071,487(A) PC GRAND THEFT,2303,38.530645,-121.467237
2112,1/10/06 1:00,3555 AUBURN BLVD,2,2A,509,MISSING PERSON,7000,38.638629,-121.381560

In [ ]:
d1 = {"Name": ["Pankaj", "Lisa", "David"], "ID": [1, 2, 3], "Role": ["CEO", "Editor", "Author"]}
df1 = pd.DataFrame(d1)

d2 = {"Name": ["Amit", "Deepak", "Ram"], "ID": [4, 2, 6], "Role": ["CEO", "Sales", "Marketing"]}
df2 = pd.DataFrame(d2)

In [ ]:
pd.merge(df1,df2,on='ID',how='inner')

  Name_x  ID  Role_x  Name_y Role_y
0   Lisa   2  Editor  Deepak  Sales

In [ ]:
pd.merge(df1,df2,on='ID',how='left')

   Name_x  ID  Role_x  Name_y Role_y
0  Pankaj   1     CEO     NaN    NaN
1    Lisa   2  Editor  Deepak  Sales
2   David   3  Author     NaN    NaN

In [ ]:
df1

     Name  ID    Role
0  Pankaj   1     CEO
1    Lisa   2  Editor
2   David   3  Author

In [ ]:
df2

     Name  ID       Role
0    Amit   4        CEO
1  Deepak   2      Sales
2     Ram   6  Marketing

In [ ]:
pd.merge(df1,df2,on='ID',how="inner")

  Name_x  ID  Role_x  Name_y Role_y
0   Lisa   2  Editor  Deepak  Sales

In [ ]:
pd.merge(df1,df2,on='ID',how="left")

   Name_x  ID  Role_x  Name_y Role_y
0  Pankaj   1     CEO     NaN    NaN
1    Lisa   2  Editor  Deepak  Sales
2   David   3  Author     NaN    NaN

In [ ]:
pd.merge(df1,df2,on='ID',how="right")

  Name_x  ID  Role_x  Name_y     Role_y
0   Lisa   2  Editor  Deepak      Sales
1    NaN   4     NaN    Amit        CEO
2    NaN   6     NaN     Ram  Marketing

In [ ]:
pd.merge(df1,df2,on='ID',how="outer")

   Name_x  ID  Role_x  Name_y     Role_y
0  Pankaj   1     CEO     NaN        NaN
1    Lisa   2  Editor  Deepak      Sales
2   David   3  Author     NaN        NaN
3     NaN   4     NaN    Amit        CEO
4     NaN   6     NaN     Ram  Marketing